// kyc-center-styles.ts — 接单中心样式（R3 token，生产文字一律 ≥11pt）。
import { StyleSheet } from "react-native";
import { color } from "../theme";

export const meStyles = StyleSheet.create({
  page: { gap: 12, paddingBottom: 40 },
  backRow: { alignSelf: "flex-start", paddingVertical: 6 },
  backText: { color: color.magenta, fontSize: 13, fontWeight: "800" },
  pageTitle: { color: color.ink, fontSize: 22, fontWeight: "900" },
  hero: { backgroundColor: color.white, borderColor: color.line, borderRadius: 18, borderWidth: 1, gap: 10, padding: 14 },
  heroHead: { alignItems: "center", flexDirection: "row", gap: 12 },
  heroAvaFallback: { alignItems: "center", backgroundColor: color.surface, borderRadius: 28, height: 56, justifyContent: "center", width: 56 },
  heroAvaLetter: { color: color.muted, fontSize: 20, fontWeight: "900" },
  heroCopy: { flex: 1, gap: 2 },
  heroName: { color: color.ink, fontSize: 17, fontWeight: "900" },
  heroCity: { color: color.muted, fontSize: 12, fontWeight: "700", lineHeight: 18 },
  heroStats: { flexDirection: "row", gap: 8 },
  heroStat: { alignItems: "center", flex: 1, gap: 2 },
  heroStatValue: { color: color.ink, fontSize: 16, fontWeight: "900" },
  heroStatLabel: { color: color.muted, fontSize: 11, fontWeight: "700" },
  inlineError: { color: color.magenta, fontSize: 12, fontWeight: "700" },
  emptyText: { color: color.muted, fontSize: 12, fontWeight: "700", lineHeight: 18 },
  kycCard: { backgroundColor: color.white, borderColor: color.line, borderRadius: 18, borderWidth: 1, padding: 14 },
  kycHead: { alignItems: "center", flexDirection: "row", gap: 12 },
  kycCopy: { flex: 1, gap: 4 },
  kycTitle: { color: color.ink, fontSize: 14.5, fontWeight: "900" },
  kycSub: { color: color.muted, fontSize: 11, fontWeight: "700", lineHeight: 16 },
  kycGo: { color: color.ink, fontSize: 13, fontWeight: "800" },
  entryRow: { alignItems: "center", backgroundColor: color.white, borderColor: color.line, borderRadius: 18, borderWidth: 1, flexDirection: "row", gap: 12, padding: 14 },
  entryCopy: { flex: 1, gap: 4 },
  entryTitle: { color: color.ink, fontSize: 14, fontWeight: "900" },
  entrySub: { color: color.muted, fontSize: 11, fontWeight: "700", lineHeight: 16 },
  entryArrow: { color: color.muted, fontSize: 16 },
  sectionTitle: { color: color.ink, fontSize: 15, fontWeight: "900", marginTop: 4 },
  skillRow: { alignItems: "center", backgroundColor: color.white, borderColor: color.line, borderRadius: 14, borderWidth: 1, flexDirection: "row", gap: 12, padding: 12 },
  skillCopy: { flex: 1, gap: 3 },
  skillName: { color: color.ink, fontSize: 13, fontWeight: "900" },
  skillSub: { color: color.muted, fontSize: 11, fontWeight: "700" },
  skillBadge: { backgroundColor: color.surface, borderRadius: 999, color: color.muted, fontSize: 11, fontWeight: "800", paddingHorizontal: 9, paddingVertical: 4 },
  skillBadgeVerified: { backgroundColor: color.proxyGreenSoft, color: color.proxyGreen },
  skillBadgeReviewing: { backgroundColor: color.warnBannerBg, color: color.warnBannerText },
  ghostBtn: { alignItems: "center", borderColor: color.line, borderRadius: 14, borderWidth: 1, paddingVertical: 12 },
  ghostBtnText: { color: color.ink, fontSize: 13, fontWeight: "800" },
});
