import { StyleSheet } from "react-native";
import { color, shadows } from "../theme";

export const styles = StyleSheet.create({
  personalSceneEntry: { alignItems: "center", alignSelf: "flex-start", backgroundColor: color.proxyPurpleSoft, borderRadius: 16, flexDirection: "row", gap: 10, marginTop: 10, paddingHorizontal: 13, paddingVertical: 12 },
  personalSceneCopy: { flexDirection: "row", alignItems: "center", gap: 10 },
  personalSceneTitle: { color: color.ink, fontSize: 14, fontWeight: "800" },
  personalSceneSub: { color: color.muted, fontSize: 11, marginTop: 2 },
  personalSceneChevron: { color: color.muted, fontSize: 23 },
  root: { backgroundColor: color.offWhite, flex: 1 },
  content: { paddingBottom: 18, paddingHorizontal: 15, paddingTop: 11 },
  orderPageHead: { alignItems: "center", flexDirection: "row", gap: 10, marginBottom: 12 },
  orderBack: { alignItems: "center", backgroundColor: color.white, borderColor: color.line, borderRadius: 12, borderWidth: 1, height: 40, justifyContent: "center", width: 40 },
  orderBackText: { color: color.ink, fontSize: 22, fontWeight: "800" },
  orderTabs: { marginBottom: 12 },
  orderTab: { backgroundColor: color.white, borderColor: color.line, borderRadius: 999, borderWidth: 1, marginRight: 7, paddingHorizontal: 13, paddingVertical: 9 },
  orderTabOn: { backgroundColor: color.ink, borderColor: color.ink },
  orderTabText: { color: color.muted, fontSize: 12, fontWeight: "800" },
  orderTabTextOn: { color: color.white },
  // R18.x CANCEL-001: a small red outline button for the
  // destructive action. Visually distinct from the
  // neutral pill tabs above so a swipe doesn't accidentally
  // cancel an order.
  orderCancelBtn: { alignSelf: "flex-end", borderColor: "#D33D5B", marginRight: 0, marginTop: 6 },
  orderCancelBtnText: { color: "#D33D5B" },
  orderCard: { backgroundColor: color.white, borderColor: color.line, borderRadius: 20, borderWidth: 1, marginBottom: 11, padding: 14, ...shadows.card },
  orderHead: { alignItems: "flex-start", flexDirection: "row", gap: 8, justifyContent: "space-between" },
  orderCopy: { flex: 1 },
  orderTitle: { color: color.ink, fontSize: 14, fontWeight: "900" },
  orderId: { color: color.muted, fontSize: 11, letterSpacing: 0.2, marginTop: 4 },
  orderBadge: { backgroundColor: "#F3F1F4", borderRadius: 999, color: "#6D6771", fontSize: 11, fontWeight: "800", overflow: "hidden", paddingHorizontal: 8, paddingVertical: 5 },
  orderBadgeLive: { backgroundColor: "#EFFFBD", color: "#3C4700" },
  orderGrid: { borderTopColor: color.line, borderTopWidth: 1, flexDirection: "row", flexWrap: "wrap", gap: 10, marginTop: 12, paddingTop: 12 },
  orderField: { width: "47%" },
  orderFieldLabel: { color: color.muted, fontSize: 11, marginBottom: 3 },
  orderFieldValue: { color: color.ink, fontSize: 12, fontWeight: "800", lineHeight: 17 },
  orderStatus: { color: color.muted, fontSize: 11, marginTop: 11 },
  orderActions: { flexDirection: "row", gap: 7, marginTop: 12 },
  orderAction: { borderColor: color.line, borderRadius: 12, borderWidth: 1, paddingHorizontal: 11, paddingVertical: 8 },
  orderActionPrimary: { backgroundColor: color.ink, borderColor: color.ink },
  orderActionText: { color: color.ink, fontSize: 11, fontWeight: "800" },
  orderActionPrimaryText: { color: color.white },
  orderNotice: { backgroundColor: "#FAF9FB", borderRadius: 14, color: color.muted, fontSize: 11, lineHeight: 16, marginTop: 12, padding: 11 },
  activityOwnedTabs: { flexDirection: "row", gap: 7, marginBottom: 12 },
  activityOwnedTab: { backgroundColor: color.white, borderColor: color.line, borderRadius: 999, borderWidth: 1, paddingHorizontal: 14, paddingVertical: 9 },
  activityOwnedTabOn: { backgroundColor: color.ink, borderColor: color.ink },
  activityOwnedTabText: { color: color.muted, fontSize: 12, fontWeight: "800" },
  activityOwnedTabTextOn: { color: color.white },
  savedIntro: { color: color.muted, fontSize: 12, lineHeight: 18, marginBottom: 12 },
  savedCard: { backgroundColor: color.white, borderColor: color.line, borderRadius: 20, borderWidth: 1, marginBottom: 11, padding: 14, ...shadows.card },
  savedRow: { alignItems: "center", flexDirection: "row", gap: 11 },
  savedThumb: { alignItems: "center", backgroundColor: "#F1EEF2", borderRadius: 14, height: 48, justifyContent: "center", width: 48 },
  savedThumbText: { color: color.ink, fontSize: 22 },
  savedMeta: { color: color.muted, fontSize: 11, lineHeight: 16, marginTop: 4 },
  meLocationRow: { alignItems: "center", flexDirection: "row", gap: 8, paddingBottom: 8, paddingHorizontal: 1, paddingTop: 3 },
  meLocationPin: { alignItems: "center", backgroundColor: "#F4EDF8", borderRadius: 10, height: 36, justifyContent: "center", width: 36 },
  meLocationCopy: { flex: 1 },
  meLocationCity: { color: color.ink, fontSize: 14, fontWeight: "800", lineHeight: 20 },
  meLocationSub: { color: color.muted, fontSize: 12, lineHeight: 17, marginTop: 2 },
  meLocationSwitch: { color: "#6D6175", fontSize: 11, fontWeight: "800" },
  pageTitleRow: { flexDirection: "row", alignItems: "center" },
  pageTitle: { color: color.ink, fontSize: 28, fontWeight: "900", lineHeight: 34, marginBottom: 4, marginTop: 8 },

  profileCard: {
    backgroundColor: color.white,
    borderColor: color.line,
    borderRadius: 20,
    borderWidth: 1,
    marginVertical: 8,
    marginBottom: 12,
    paddingHorizontal: 16,
    paddingVertical: 16
  },
  profileTop: { alignItems: "center", flexDirection: "row", gap: 10 },
  profileAvatar: {
    alignItems: "center",
    borderRadius: 23,
    height: 46,
    justifyContent: "center",
    overflow: "hidden",
    width: 46
  },
  profileAvatarText: { color: color.white, fontSize: 18, fontWeight: "900" },
  profileCopy: { flex: 1 },
  profileName: { color: color.ink, fontSize: 15, fontWeight: "800", lineHeight: 21 },
  profileMeta: { alignItems: "center", flexDirection: "row", gap: 5, marginTop: 3 },
  profileMetaText: { color: color.muted, fontSize: 12, lineHeight: 17 },
  profileVerifyDot: { alignItems: "center", backgroundColor: "#EFE8FF", borderRadius: 6, height: 12, justifyContent: "center", width: 12 },
  profileVerifyText: { color: "#6B35B6", fontSize: 11, fontWeight: "900", includeFontPadding: false, lineHeight: 15 },
  profileStatus: {
    backgroundColor: "#F1FFD7",
    borderRadius: 999,
    paddingHorizontal: 9,
    paddingVertical: 7
  },
  profileStatusText: { color: "#465C00", fontSize: 11, fontWeight: "900" },
  profileSocial: {
    alignItems: "center",
    borderTopColor: "#F1EDF3",
    borderTopWidth: 1,
    flexDirection: "row",
    gap: 6,
    marginTop: 11,
    paddingTop: 9
  },
  profileSocialBadge: {
    alignItems: "center",
    backgroundColor: "#FBFAFC",
    borderColor: "#EBE6EE",
    borderRadius: 9,
    borderWidth: 1,
    height: 25,
    justifyContent: "center",
    minWidth: 25,
    paddingHorizontal: 6
  },
  profileSocialBadgeOn: { backgroundColor: "#FAF7FF", borderColor: "#D8C8F0" },
  profileSocialBadgeDark: { backgroundColor: "#17131F" },
  profileSocialBadgeText: { color: "#564D5B", fontSize: 11, fontWeight: "900" },
  profileSocialMore: { color: "#8B8291", fontSize: 11, marginLeft: 6 },

  bizAlert: {
    alignItems: "center",
    backgroundColor: color.ink,
    borderRadius: 17,
    flexDirection: "row",
    gap: 10,
    marginBottom: 4,
    marginTop: 8,
    padding: 13
  },
  bizAlertMark: {
    alignItems: "center",
    backgroundColor: "rgba(212,255,61,0.16)",
    borderRadius: 12,
    height: 40,
    justifyContent: "center",
    width: 40
  },
  bizAlertMarkText: { color: color.lime, fontSize: 17 },
  bizAlertCopy: { flex: 1 },
  bizAlertTitle: { color: color.white, fontSize: 11, fontWeight: "800" },
  bizAlertDesc: { color: "rgba(255,255,255,0.6)", fontSize: 11, lineHeight: 15, marginTop: 3 },
  bizAlertTag: { color: "#CBBFE0", fontSize: 11, fontWeight: "700" },

  identityCard: {
    alignItems: "center",
    backgroundColor: color.white,
    borderColor: color.line,
    borderRadius: 17,
    borderWidth: 1,
    flexDirection: "row",
    gap: 9,
    marginVertical: 8,
    padding: 11
  },
  identityAvatar: {
    alignItems: "center",
    borderRadius: 20,
    height: 40,
    justifyContent: "center",
    overflow: "hidden",
    width: 40
  },
  identityAvatarSolid: { backgroundColor: "#17131F" },
  identityAvatarText: { color: color.white, fontSize: 16, fontWeight: "900" },
  identityCopy: { flex: 1 },
  identityName: { color: color.ink, fontSize: 15, fontWeight: "800", lineHeight: 21 },
  identityDesc: { color: color.muted, fontSize: 12, lineHeight: 17, marginTop: 2 },
  identityButton: { backgroundColor: color.white, borderColor: color.line, borderRadius: 999, borderWidth: 1, minHeight: 44, paddingHorizontal: 12, paddingVertical: 10 },
  identityButtonText: { color: color.ink, fontSize: 14, fontWeight: "800" },

  section: { marginTop: 10 },
  sectionHead: {
    alignItems: "flex-end",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 7,
    paddingHorizontal: 1
  },
  sectionTitle: { color: color.ink, fontSize: 17, fontWeight: "800", lineHeight: 24 },
  sectionHint: { color: color.muted, fontSize: 11, lineHeight: 15 },

  serviceRow: {
    alignItems: "center",
    backgroundColor: color.white,
    borderColor: "rgba(20,18,31,0.035)",
    borderRadius: 20,
    borderWidth: 1,
    flexDirection: "row",
    gap: 12,
    marginBottom: 6,
    minHeight: 72,
    padding: 12
  },
  serviceIcon: {
    alignItems: "center",
    backgroundColor: color.lime,
    borderRadius: 14,
    height: 44,
    justifyContent: "center",
    width: 44
  },
  serviceLogoBox: { backgroundColor: "#08090A" },
  serviceLogo: { borderRadius: 9, height: 36, width: 36 },
  voucherMenuGlyph: { alignItems: "center", height: 36, justifyContent: "center", width: 36 },
  voucherCup: { borderRadius: 4, borderWidth: 2.4, height: 14, left: 8, position: "absolute", top: 16, width: 17 },
  voucherCupHandle: { borderRadius: 7, borderWidth: 2.4, height: 9, left: 23, position: "absolute", top: 20, width: 8 },
  voucherSteam: { borderRadius: 4, height: 9, position: "absolute", top: 6, transform: [{ rotate: "18deg" }], width: 2.4 },
  voucherPin: { alignItems: "center", backgroundColor: color.white, borderColor: color.line, borderRadius: 17, borderWidth: 1, flexDirection: "row", gap: 9, marginBottom: 4, marginTop: -3, padding: 11, ...shadows.card },
  voucherPinMark: { alignItems: "center", backgroundColor: color.lime, borderRadius: 12, height: 40, justifyContent: "center", width: 40 },
  voucherPinCopy: { flex: 1, minWidth: 0 },
  voucherPinTitle: { color: color.ink, fontSize: 11, fontWeight: "800" },
  voucherPinDesc: { color: color.muted, fontSize: 11, marginTop: 3 },
  voucherPinRight: { alignItems: "flex-end" },
  voucherPinCount: { color: color.ink, fontSize: 11, fontWeight: "800" },
  voucherPinAction: { color: color.muted, fontSize: 11, marginTop: 3 },
  enterpriseHero: { backgroundColor: color.ink, borderRadius: 18, marginTop: 4, padding: 14 },
  enterpriseSkillId: { color: color.lime, fontSize: 11, fontWeight: "900", letterSpacing: 0.7 },
  enterpriseHeroTitle: { color: color.white, fontSize: 19, fontWeight: "700", marginTop: 7 },
  enterpriseHeroText: { color: "rgba(255,255,255,0.7)", fontSize: 11, lineHeight: 15, marginTop: 5 },
  enterpriseRuntime: { backgroundColor: "#F4EEF7", borderRadius: 14, marginTop: 8, padding: 11 },
  enterpriseRuntimeTitle: { color: color.ink, fontSize: 11, fontWeight: "900" },
  enterpriseRuntimeText: { color: color.muted, fontSize: 11, lineHeight: 15, marginTop: 4 },
  enterpriseQuickGrid: { flexDirection: "row", flexWrap: "wrap", gap: 7, marginTop: 10 },
  enterpriseQuick: { backgroundColor: color.white, borderColor: color.line, borderRadius: 14, borderWidth: 1, minHeight: 84, padding: 10, width: "48.8%", ...shadows.card },
  enterpriseQuickTitle: { color: color.ink, fontSize: 11, fontWeight: "900" },
  enterpriseQuickDesc: { color: color.muted, fontSize: 11, lineHeight: 15, marginTop: 5 },
  enterpriseAssetTray: { flexDirection: "row", gap: 7, marginTop: 7 },
  enterpriseAsset: { alignItems: "center", backgroundColor: color.white, borderColor: color.line, borderRadius: 12, borderWidth: 1, flex: 1, minHeight: 61, padding: 7 },
  enterpriseAssetThumb: { color: "#6F37B9", fontSize: 16 },
  enterpriseAssetThumbImg: { borderRadius: 8, height: 40, width: "100%" },
  enterpriseAssetText: { color: color.ink, fontSize: 11, fontWeight: "800", marginTop: 4 },
  enterpriseAssetActions: { flexDirection: "row", gap: 7 },
  enterpriseDraft: { backgroundColor: color.white, borderColor: color.line, borderRadius: 16, borderWidth: 1, marginTop: 10, padding: 11, ...shadows.card },
  enterpriseDraftTitle: { color: color.ink, fontSize: 11, fontWeight: "900", marginBottom: 5 },
  enterpriseDraftRow: { alignItems: "center", borderTopColor: color.line, borderTopWidth: 1, flexDirection: "row", gap: 8, paddingVertical: 8 },
  enterpriseDraftCopy: { flex: 1 },
  enterpriseDraftName: { color: color.ink, fontSize: 11, fontWeight: "800" },
  enterpriseDraftMeta: { color: color.muted, fontSize: 11, lineHeight: 15, marginTop: 2 },
  enterpriseDraftState: { color: "#536D00", fontSize: 11, fontWeight: "900" },
  enterpriseProgressNote: { backgroundColor: "#F4EEF7" },
  enterpriseMetrics: { flexDirection: "row", gap: 7, marginTop: 9 },
  enterpriseMetric: { alignItems: "center", backgroundColor: color.white, borderColor: color.line, borderRadius: 14, borderWidth: 1, flex: 1, paddingVertical: 12, ...shadows.card },
  enterpriseMetricValue: { color: color.ink, fontSize: 16, fontWeight: "900" },
  enterpriseMetricLabel: { color: color.muted, fontSize: 11, marginTop: 3 },
  serviceCopy: { flex: 1 },
  serviceLabel: { color: color.ink, fontSize: 15, fontWeight: "800", lineHeight: 21 },
  serviceDesc: { color: color.muted, fontSize: 11, lineHeight: 15, marginTop: 2 },
  chev: { color: "#A59CAB", fontSize: 24 },

  contextLine: {
    alignItems: "center",
    backgroundColor: "#F4EEF7",
    borderRadius: 13,
    flexDirection: "row",
    justifyContent: "space-between",
    marginVertical: 7,
    paddingHorizontal: 9,
    paddingVertical: 8
  },
  contextLineText: { color: color.ink, fontSize: 11, fontWeight: "700" },
  contextLineAction: { color: "#574361", fontSize: 11, fontWeight: "900" },

  signOut: { alignItems: "center", marginBottom: 2, marginTop: 13, paddingVertical: 2 },
  signOutText: { color: "#A84A69", fontSize: 11, fontWeight: "800" },

  subPageBack: { marginBottom: 10, paddingVertical: 4 },
  subPageBackText: { color: color.magenta, fontSize: 12, fontWeight: "700" },
  subPageIcon: {
    alignItems: "center",
    backgroundColor: color.lime,
    borderRadius: 16,
    height: 56,
    justifyContent: "center",
    marginBottom: 12,
    width: 56
  },
  subPageIconText: { color: color.ink, fontSize: 28 },
  subPageTitle: { color: color.ink, fontSize: 18, fontWeight: "800", marginBottom: 6 },
  subPageSub: { color: color.muted, fontSize: 12, lineHeight: 18, marginBottom: 16 },
  subPageDesc: { color: color.muted, fontSize: 12, lineHeight: 18, marginBottom: 16 },
  profileManageRow: { flexDirection: "row", alignItems: "center", padding: 12, backgroundColor: color.white, borderRadius: 10, borderWidth: 1, borderColor: color.line, marginBottom: 12 },
  profileManageAva: { width: 88, height: 88, borderRadius: 44, backgroundColor: color.magenta, alignItems: "center", justifyContent: "center", marginRight: 12, overflow: "hidden" },
  profileManageAvaLetter: { color: color.ink, fontSize: 30, fontWeight: "800" },
  profileManageCopy: { flex: 1 },
  profileManageName: { color: color.ink, fontSize: 15, fontWeight: "700" },
  profileManageHandle: { color: color.muted, fontSize: 11, marginTop: 1 },
  profileManageCity: { color: color.muted, fontSize: 11, marginTop: 1 },
  profileManageEdit: { paddingHorizontal: 10, paddingVertical: 6, borderRadius: 6, borderWidth: 1, borderColor: color.line },
  profileManageEditText: { color: color.ink, fontSize: 11, fontWeight: "600" },
  profileManageStatusRow: { flexDirection: "row", alignItems: "center", padding: 12, backgroundColor: color.white, borderRadius: 10, borderWidth: 1, borderColor: color.line, marginBottom: 8 },
  profileManageStatusDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: "#10b981", marginRight: 10 },
  profileManageStatusCopy: { flex: 1 },
  profileManageStatusLabel: { color: color.muted, fontSize: 11, fontWeight: "600" },
  profileManageStatusValue: { color: color.ink, fontSize: 14, fontWeight: "700", marginTop: 2 },
  profileManageStatusChev: { color: color.muted, fontSize: 18 },
  profileManageStatusList: { marginTop: 4 },
  profileManageStatusItem: { padding: 12, backgroundColor: color.white, borderRadius: 8, borderWidth: 1, borderColor: color.line, marginBottom: 6 },
  profileManageStatusItemOn: { backgroundColor: color.violet, borderColor: color.magenta },
  profileManageStatusItemText: { color: color.ink, fontSize: 14, fontWeight: "600" },
  profileManageStatusItemTextOn: { color: color.magenta, fontWeight: "700" },
  profileManageStatusItemDesc: { color: color.muted, fontSize: 11, marginTop: 2 },
  subPagePlaceholder: {
    backgroundColor: color.white,
    borderColor: color.line,
    borderRadius: 16,
    borderWidth: 1,
    padding: 18,
    ...shadows.card
  },
  subPagePlaceholderText: { color: color.muted, fontSize: 11, lineHeight: 17, textAlign: "center" },
  subPagePlaceholderHint: { color: "#A9A2B0", fontSize: 11, lineHeight: 15, marginTop: 8, textAlign: "center" },

  appBehaviorTitle: { color: color.ink, fontSize: 19, fontWeight: "700", marginBottom: 4, marginTop: 8 },
  appBehaviorCard: {
    backgroundColor: color.white,
    borderColor: "rgba(20,18,31,0.035)",
    borderRadius: 14,
    borderWidth: 1,
    marginTop: 6,
    padding: 10,
    ...shadows.card
  },
  appBehaviorCardDark: { backgroundColor: color.ink, borderColor: color.ink },
  appBehaviorCardTitle: { color: color.ink, fontSize: 11, fontWeight: "700" },
  appBehaviorCardTitleDark: { color: color.white },
  appBehaviorCardDesc: { color: color.muted, fontSize: 11, lineHeight: 15, marginTop: 3 },
  appBehaviorCardDescDark: { color: "rgba(255,255,255,0.67)" },
  appBehaviorActions: { flexDirection: "row", flexWrap: "wrap", gap: 7, marginTop: 10 },
  appBehaviorAction: {
    alignItems: "center",
    backgroundColor: color.white,
    borderColor: color.line,
    borderRadius: 999,
    borderWidth: 1,
    flexGrow: 1,
    minWidth: "46%",
    paddingHorizontal: 9,
    paddingVertical: 8
  },
  appBehaviorActionPrimary: { backgroundColor: color.ink, borderColor: color.ink },
  appBehaviorActionDanger: { backgroundColor: "#FFF6F8", borderColor: "#F5DDE5" },
  appBehaviorActionText: { color: color.ink, fontSize: 11, fontWeight: "800" },
  appBehaviorActionPrimaryText: { color: color.white, fontSize: 11, fontWeight: "800" },
  appBehaviorActionDangerText: { color: "#A84A69", fontSize: 11, fontWeight: "800" },
  appBehaviorReturn: { alignItems: "center", backgroundColor: color.magenta, borderRadius: 999, marginTop: 10, paddingVertical: 10 },
  appBehaviorReturnText: { color: color.white, fontSize: 11, fontWeight: "800" },

  detailTitle: { color: color.ink, fontSize: 19, fontWeight: "700", marginTop: 8 },
  detailSub: { color: color.muted, fontSize: 11, lineHeight: 15, marginBottom: 8, marginTop: 3 },
  socialAccountsContent: { paddingBottom: 36, paddingHorizontal: 18, paddingTop: 10 },
  socialAccountsTitle: { color: color.ink, fontSize: 29, fontWeight: "900", letterSpacing: -0.6, lineHeight: 34 },
  socialAccountsSub: { color: color.muted, fontSize: 14, lineHeight: 21, marginBottom: 16, marginTop: 7 },
  socialAccountList: { borderTopColor: color.line, borderTopWidth: 1, marginTop: 12 },
  socialAccountRow: { alignItems: "center", borderBottomColor: color.line, borderBottomWidth: 1, flexDirection: "row", gap: 13, minHeight: 82 },
  socialAccountIcon: { alignItems: "center", backgroundColor: "#F3EEF8", borderRadius: 14, height: 44, justifyContent: "center", width: 44 },
  socialAccountIconDark: { backgroundColor: "#111" },
  socialAccountIconText: { color: "#6E3DB7", fontSize: 13, fontWeight: "900" },
  socialAccountIconTextDark: { color: color.white },
  socialAccountCopy: { flex: 1, minWidth: 0 },
  socialAccountName: { color: color.ink, fontSize: 15, fontWeight: "900" },
  socialAccountHandle: { color: "#6E6872", fontSize: 12, marginTop: 4 },
  socialAccountUrl: { color: color.muted, fontSize: 11, marginTop: 3 },
  socialAccountTrailing: { alignItems: "center", flexDirection: "row", gap: 7 },
  socialAccountState: { backgroundColor: "#F5F2F6", borderRadius: 999, paddingHorizontal: 10, paddingVertical: 7 },
  socialAccountStateActive: { backgroundColor: "#FFF1F6" },
  socialAccountStateText: { color: "#766F79", fontSize: 11, fontWeight: "900" },
  socialAccountStateTextActive: { color: color.magenta },
  socialAccountChev: { color: "#B6AFB9", fontSize: 19 },
  socialSettingsHead: { alignItems: "center", flexDirection: "row", justifyContent: "space-between", marginBottom: 8, marginTop: 24 },
  socialSettingsTitle: { color: color.ink, fontSize: 13, fontWeight: "800" },
  socialSettingsHint: { color: color.muted, fontSize: 11 },
  socialSettingRow: { alignItems: "center", borderBottomColor: color.line, borderBottomWidth: 1, flexDirection: "row", gap: 12, paddingVertical: 15 },
  socialSettingName: { color: color.ink, fontSize: 14, fontWeight: "800" },
  socialSettingDesc: { color: "#6E6872", fontSize: 12, lineHeight: 18, marginTop: 4 },
  socialSwitch: { backgroundColor: "#D9D4DC", borderRadius: 999, height: 28, padding: 3, width: 48 },
  socialSwitchOn: { backgroundColor: color.ink },
  socialSwitchDot: { backgroundColor: color.white, borderRadius: 11, height: 22, width: 22 },
  socialSwitchDotOn: { backgroundColor: "#FF5C99", marginLeft: 20 },
  socialShareBox: { borderTopColor: color.line, borderTopWidth: 1, marginTop: 22, paddingTop: 0 },
  socialShareLine: { alignItems: "center", flexDirection: "row", gap: 10, paddingVertical: 12 },
  socialShareLink: { backgroundColor: color.white, borderColor: color.line, borderRadius: 13, borderWidth: 1, color: "#5F5963", flex: 1, fontSize: 12, padding: 11 },
  socialShareButton: { alignItems: "center", backgroundColor: color.ink, borderRadius: 12, height: 40, justifyContent: "center", paddingHorizontal: 14 },
  socialShareButtonText: { color: color.white, fontSize: 12, fontWeight: "900" },
  socialShareNote: { color: "#A19AA5", fontSize: 11, lineHeight: 16, marginTop: 2 },
  socialEditorOverlay: { backgroundColor: "rgba(16,12,18,0.28)", flex: 1, justifyContent: "flex-end" },
  socialEditorSheet: { backgroundColor: color.white, borderTopLeftRadius: 24, borderTopRightRadius: 24, paddingBottom: 30, paddingHorizontal: 20, paddingTop: 16 },
  socialEditorGrabber: { alignSelf: "center", backgroundColor: "#D7D1D9", borderRadius: 999, height: 4, marginBottom: 14, width: 34 },
  socialEditorHead: { alignItems: "center", flexDirection: "row", justifyContent: "space-between", marginBottom: 8 },
  socialEditorTitle: { color: color.ink, fontSize: 22, fontWeight: "900" },
  socialEditorClose: { alignItems: "center", backgroundColor: "#F4F1F5", borderRadius: 17, height: 34, justifyContent: "center", width: 34 },
  socialEditorCloseText: { color: "#5D5661", fontSize: 20 },
  socialEditorNote: { color: color.muted, fontSize: 12, lineHeight: 17, marginBottom: 2 },
  socialEditorLabel: { color: color.muted, fontSize: 11, fontWeight: "800", marginBottom: 7, marginTop: 14 },
  socialEditorInput: { backgroundColor: color.white, borderColor: color.line, borderRadius: 12, borderWidth: 1, color: color.ink, height: 44, paddingHorizontal: 12 },
  socialVisibilityRow: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 1 },
  socialVisibilityButton: { borderColor: color.line, borderRadius: 999, borderWidth: 1, paddingHorizontal: 11, paddingVertical: 8 },
  socialVisibilityButtonOn: { backgroundColor: color.ink, borderColor: color.ink },
  socialVisibilityText: { color: "#625B66", fontSize: 11, fontWeight: "800" },
  socialVisibilityTextOn: { color: color.white },
  socialOpenLink: { borderTopColor: color.line, borderTopWidth: 1, flexDirection: "row", justifyContent: "space-between", marginTop: 12, paddingVertical: 12 },
  socialOpenLinkText: { color: "#4D4751", fontSize: 12, fontWeight: "800" },
  socialSave: { alignItems: "center", backgroundColor: color.ink, borderRadius: 14, height: 48, justifyContent: "center", marginTop: 6 },
  socialSaveText: { color: color.white, fontSize: 14, fontWeight: "900" },
  channelCard: { alignItems: "center", backgroundColor: color.white, borderColor: color.line, borderRadius: 17, borderWidth: 1, flexDirection: "row", gap: 10, marginVertical: 4, padding: 11, ...shadows.card },
  channelMark: { alignItems: "center", backgroundColor: "#F5F1F8", borderRadius: 11, height: 36, justifyContent: "center", width: 36 },
  channelMarkLinked: { backgroundColor: "#F1E8FF" },
  channelMarkText: { color: "#6F37B9", fontSize: 11, fontWeight: "900" },
  channelCopy: { flex: 1 },
  channelName: { color: color.ink, fontSize: 11, fontWeight: "800" },
  channelAccount: { color: color.muted, fontSize: 11, marginTop: 2 },
  channelStatus: { borderRadius: 999, paddingHorizontal: 8, paddingVertical: 5 },
  channelStatusOn: { backgroundColor: "#F1FFD7" },
  channelStatusOff: { backgroundColor: "#F4EFF7" },
  channelStatusText: { fontSize: 11, fontWeight: "900" },
  channelStatusTextOn: { color: "#506900" },
  channelStatusTextOff: { color: "#756A7B" },
  detailSectionHead: { alignItems: "center", flexDirection: "row", justifyContent: "space-between", marginTop: 11, paddingHorizontal: 1 },
  detailSectionTitle: { color: color.ink, fontSize: 11, fontWeight: "700" },
  detailSectionHint: { color: color.muted, fontSize: 11 },
  socialDetailRow: { alignItems: "center", backgroundColor: color.white, borderColor: "rgba(20,18,31,0.04)", borderRadius: 15, borderWidth: 1, flexDirection: "row", gap: 9, marginTop: 6, padding: 11 },
  socialDetailIcon: { alignItems: "center", backgroundColor: "#F5F1F8", borderRadius: 10, height: 31, justifyContent: "center", width: 31 },
  socialDetailIconText: { color: "#6F37B9", fontSize: 11, fontWeight: "900" },
  socialDetailCopy: { flex: 1 },
  socialDetailLabel: { color: color.ink, fontSize: 11, fontWeight: "800" },
  socialDetailDesc: { color: color.muted, fontSize: 11, lineHeight: 15, marginTop: 2 },
  socialDetailChev: { color: "#A59EAA", fontSize: 15 },
  visibilityLadder: { backgroundColor: color.white, borderColor: color.line, borderRadius: 17, borderWidth: 1, marginTop: 8, overflow: "hidden", ...shadows.card },
  visibilityStep: { alignItems: "center", borderBottomColor: color.line, borderBottomWidth: 1, flexDirection: "row", gap: 8, padding: 10 },
  visibilityIndex: { alignItems: "center", backgroundColor: "#F1E8FF", borderRadius: 10, height: 24, justifyContent: "center", width: 24 },
  visibilityIndexText: { color: "#6B35B6", fontSize: 11, fontWeight: "900" },
  visibilityCopy: { flex: 1 },
  visibilityTitle: { color: color.ink, fontSize: 11, fontWeight: "800" },
  visibilityDesc: { color: color.muted, fontSize: 11, lineHeight: 15, marginTop: 2 },
  visibilityTag: { color: "#756A7B", fontSize: 11, fontWeight: "800" },
  funnelCard: { backgroundColor: color.white, borderColor: color.line, borderRadius: 18, borderWidth: 1, marginVertical: 8, padding: 12, ...shadows.card },
  funnelRow: { alignItems: "center", flexDirection: "row", gap: 8, marginVertical: 5 },
  funnelLabel: { color: color.muted, fontSize: 11, width: 58 },
  funnelTrack: { backgroundColor: "#F1EDF3", borderRadius: 999, flex: 1, height: 7, overflow: "hidden" },
  funnelBar: { borderRadius: 999, height: 7 },
  funnelValue: { color: color.ink, fontSize: 11, fontWeight: "800", textAlign: "right", width: 34 },
  sourceTable: { backgroundColor: color.white, borderColor: color.line, borderRadius: 17, borderWidth: 1, marginTop: 8, overflow: "hidden", ...shadows.card },
  sourceRow: { borderBottomColor: color.line, borderBottomWidth: 1, flexDirection: "row", paddingHorizontal: 11, paddingVertical: 9 },
  sourceHead: { backgroundColor: color.surface },
  sourceHeadText: { color: color.muted, flex: 1, fontSize: 11, fontWeight: "800", textAlign: "right" },
  sourceName: { color: color.ink, flex: 1, fontSize: 11, fontWeight: "700" },
  sourceValue: { color: color.ink, flex: 1, fontSize: 11, fontWeight: "800", textAlign: "right" },
  infoNote: { backgroundColor: "#F4EEF7", borderRadius: 14, marginTop: 9, padding: 11 },
  infoNoteTitle: { color: color.ink, fontSize: 11, fontWeight: "800" },
  infoNoteText: { color: color.muted, fontSize: 11, lineHeight: 15, marginTop: 3 },
  friendPageHead: { alignItems: "flex-start", flexDirection: "row", justifyContent: "space-between" },
  closeIcon: { alignItems: "center", backgroundColor: color.white, borderColor: color.line, borderRadius: 12, borderWidth: 1, height: 28, justifyContent: "center", marginTop: 7, width: 28 },
  closeIconText: { color: color.ink, fontSize: 16, lineHeight: 20 },
  friendMethodGrid: { flexDirection: "row", flexWrap: "wrap", gap: 7, marginTop: 8 },
  friendMethod: { backgroundColor: color.white, borderColor: color.line, borderRadius: 15, borderWidth: 1, minHeight: 100, padding: 11, width: "48.8%", ...shadows.card },
  friendMethodIcon: { color: "#6F37B9", fontSize: 16, fontWeight: "900" },
  friendMethodTitle: { color: color.ink, fontSize: 11, fontWeight: "800", marginTop: 10 },
  friendMethodDesc: { color: color.muted, fontSize: 11, lineHeight: 15, marginTop: 3 },
  prototypeCard: { backgroundColor: color.white, borderColor: "rgba(20,18,31,0.035)", borderRadius: 14, borderWidth: 1, marginTop: 6, padding: 10, ...shadows.card },
  prototypeCardTitle: { color: color.ink, fontSize: 11, fontWeight: "700" },
  prototypeCardDesc: { color: color.muted, fontSize: 11, lineHeight: 15, marginTop: 3 },
  trustedExecutorCard: { backgroundColor: color.white, borderColor: color.line, borderRadius: 17, borderWidth: 1, marginTop: 8, padding: 12, ...shadows.card },
  trustedExecutorTop: { alignItems: "center", flexDirection: "row" },
  trustedExecutorAvatar: { alignItems: "center", borderRadius: 24, height: 48, justifyContent: "center", width: 48 },
  trustedExecutorAvatarText: { color: color.white, fontSize: 19, fontWeight: "900" },
  trustedExecutorCopy: { flex: 1, marginLeft: 9 },
  trustedExecutorName: { color: color.ink, fontSize: 11, fontWeight: "800" },
  trustedExecutorMeta: { color: color.muted, fontSize: 11, marginTop: 3 },
  trustedExecutorRating: { color: color.ink, fontSize: 18, fontWeight: "900" },
  trustedExecutorStats: { flexDirection: "row", gap: 6, marginTop: 11 },
  trustedExecutorStat: { backgroundColor: "#F6F1F8", borderRadius: 10, flex: 1, minHeight: 54, paddingHorizontal: 8, paddingTop: 8 },
  trustedExecutorStatValue: { color: color.ink, fontSize: 11, fontWeight: "900" },
  trustedExecutorStatLabel: { color: color.muted, fontSize: 11, marginTop: 5 },
  trustedSuggestion: { backgroundColor: "#FBF9FC", borderColor: color.line, borderRadius: 17, borderWidth: 1, marginTop: 10, padding: 12, ...shadows.card },
  trustedSuggestionHead: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" },
  trustedSuggestionTitle: { color: color.ink, fontSize: 11, fontWeight: "900" },
  trustedSuggestionHint: { color: color.muted, fontSize: 11, fontWeight: "700" },
  trustedSuggestionBody: { backgroundColor: color.white, borderRadius: 12, marginTop: 9, padding: 11 },
  trustedSuggestionBodyTitle: { color: color.ink, fontSize: 11, fontWeight: "800" },
  trustedSuggestionBodyText: { color: color.muted, fontSize: 11, lineHeight: 15, marginTop: 4 },
  trustedInviteTouchable: { borderRadius: 14, marginTop: 12, overflow: "hidden" },
  trustedInvite: { alignItems: "center", borderRadius: 14, justifyContent: "center", minHeight: 51 },
  trustedInviteText: { color: color.white, fontSize: 11, fontWeight: "900" },
  trustedReturn: { alignItems: "center", backgroundColor: color.white, borderColor: color.line, borderRadius: 14, borderWidth: 1, justifyContent: "center", marginTop: 8, minHeight: 51 },
  trustedReturnText: { color: color.ink, fontSize: 11, fontWeight: "800" },
  diagnosticTitleRow: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" },
  diagnosticTag: { backgroundColor: "#F3EAFD", borderRadius: 999, paddingHorizontal: 9, paddingVertical: 5 },
  diagnosticTagText: { color: "#7039BE", fontSize: 11, fontWeight: "900" },
  diagnosticHero: { backgroundColor: "#211B2D", borderRadius: 20, marginTop: 10, padding: 14 },
  diagnosticHeroTop: { flexDirection: "row", justifyContent: "space-between" },
  diagnosticHeroTitle: { color: color.white, fontSize: 16, fontWeight: "900" },
  diagnosticHeroText: { color: "#D8D1E0", fontSize: 11, lineHeight: 15, marginTop: 5, maxWidth: 260 },
  diagnosticScore: { color: color.white, fontSize: 26, fontWeight: "900", textAlign: "right" },
  diagnosticScoreLabel: { color: "#D8D1E0", fontSize: 11, fontWeight: "700", marginTop: 2, textAlign: "right" },
  diagnosticMetrics: { flexDirection: "row", gap: 6, marginTop: 12 },
  diagnosticMetric: { backgroundColor: "#3A304A", borderRadius: 10, flex: 1, minHeight: 54, padding: 8 },
  diagnosticMetricValue: { color: color.white, fontSize: 12, fontWeight: "900" },
  diagnosticMetricLabel: { color: "#D8D1E0", fontSize: 11, marginTop: 7 },
  diagnosticInsightGrid: { flexDirection: "row", gap: 7, marginTop: 9 },
  diagnosticInsight: { backgroundColor: color.white, borderColor: color.line, borderRadius: 15, borderWidth: 1, flex: 1, minHeight: 115, padding: 10, ...shadows.card },
  diagnosticInsightKicker: { color: color.muted, fontSize: 11, fontWeight: "800" },
  diagnosticInsightValue: { color: color.ink, fontSize: 20, fontWeight: "900", marginTop: 7 },
  diagnosticInsightText: { color: color.muted, fontSize: 11, lineHeight: 15, marginTop: 6 },
  diagnosticActions: { backgroundColor: color.white, borderColor: color.line, borderRadius: 17, borderWidth: 1, marginTop: 10, padding: 11, ...shadows.card },
  diagnosticActionsHead: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" },
  diagnosticActionsTitle: { color: color.ink, fontSize: 11, fontWeight: "900" },
  diagnosticActionsHint: { color: color.muted, fontSize: 11, fontWeight: "700" },
  diagnosticActionItem: { backgroundColor: "#FCFBFD", borderRadius: 12, marginTop: 8, padding: 10 },
  diagnosticActionTitle: { color: color.ink, fontSize: 11, fontWeight: "800" },
  diagnosticActionText: { color: color.muted, fontSize: 11, lineHeight: 15, marginTop: 4 },
  diagnosticActionButtons: { flexDirection: "row", gap: 7, marginTop: 10 },
  diagnosticCreate: { alignItems: "center", backgroundColor: color.ink, borderRadius: 10, flex: 1, paddingVertical: 9 },
  diagnosticCreateText: { color: color.white, fontSize: 11, fontWeight: "900" },
  diagnosticFind: { alignItems: "center", backgroundColor: "#F3EEF8", borderRadius: 10, flex: 1, paddingVertical: 9 },
  diagnosticFindText: { color: color.ink, fontSize: 11, fontWeight: "900" },
  diagnosticRecipe: { borderColor: "#D8CBDD", borderRadius: 16, borderStyle: "dashed", borderWidth: 1, marginTop: 10, padding: 11 },
  diagnosticRecipeTitle: { color: color.ink, fontSize: 11, fontWeight: "900" },
  diagnosticRecipeText: { color: color.muted, fontSize: 11, lineHeight: 15, marginTop: 4 },
  primaryCta: { alignItems: "center", backgroundColor: color.ink, borderRadius: 999, marginTop: 10, paddingVertical: 10 },
  primaryCtaText: { color: color.white, fontSize: 11, fontWeight: "800" },
  lightCta: { alignItems: "center", backgroundColor: color.white, borderColor: color.line, borderRadius: 999, borderWidth: 1, marginTop: 7, paddingVertical: 10 },
  lightCtaText: { color: color.ink, fontSize: 11, fontWeight: "800" },
  fallbackSection: { marginTop: 3 },
  messagesHead: { alignItems: "flex-start", flexDirection: "row", justifyContent: "space-between" },
  messagesHeadActions: { flexDirection: "row", gap: 6, marginTop: 7 },
  messageIconButton: { alignItems: "center", backgroundColor: color.white, borderColor: color.line, borderRadius: 11, borderWidth: 1, height: 28, justifyContent: "center", position: "relative", width: 28 },
  messageIconText: { color: color.ink, fontSize: 13, fontWeight: "900" },
  messageNoticeDot: { backgroundColor: color.magenta, borderRadius: 4, height: 7, position: "absolute", right: 2, top: 2, width: 7 },
  messageTabs: { backgroundColor: "#F1EDF3", borderRadius: 12, flexDirection: "row", marginTop: 8, padding: 3 },
  messageTab: { alignItems: "center", flex: 1, paddingVertical: 7 },
  messageTabActive: { alignItems: "center", backgroundColor: color.white, borderRadius: 9, flex: 1, paddingVertical: 7 },
  messageTabText: { color: color.muted, fontSize: 11, fontWeight: "800" },
  messageTabActiveText: { color: color.ink, fontSize: 11, fontWeight: "900" },
  messageThread: { alignItems: "center", backgroundColor: color.white, borderBottomColor: color.line, borderBottomWidth: 1, flexDirection: "row", gap: 9, paddingVertical: 10 },
  messageAvatar: { alignItems: "center", backgroundColor: "#F1E8FF", borderRadius: 13, height: 38, justifyContent: "center", width: 38 },
  messageAvatarSoft: { backgroundColor: "#F5F1F8" },
  messageAvatarDark: { backgroundColor: color.ink },
  messageAvatarText: { color: color.ink, fontSize: 12, fontWeight: "900" },
  messageThreadCopy: { flex: 1 },
  messageThreadTop: { alignItems: "center", flexDirection: "row", gap: 5 },
  messageThreadName: { color: color.ink, fontSize: 11, fontWeight: "800" },
  messageContext: { backgroundColor: "#F1EDF3", borderRadius: 999, color: "#756A7B", fontSize: 11, fontWeight: "800", overflow: "hidden", paddingHorizontal: 5, paddingVertical: 2 },
  messageThreadPreview: { color: color.muted, fontSize: 11, marginTop: 3 },
  messageThreadMeta: { alignItems: "flex-end", gap: 4 },
  messageTime: { color: color.muted, fontSize: 11 },
  messageUnread: { alignItems: "center", backgroundColor: color.magenta, borderRadius: 8, height: 16, justifyContent: "center", minWidth: 16, paddingHorizontal: 4 },
  messageUnreadText: { color: color.white, fontSize: 11, fontWeight: "900" },
  messageChev: { color: "#A59EAA", fontSize: 16 },

  walletDarkCard: {
    backgroundColor: color.ink,
    borderRadius: 16,
    marginBottom: 10,
    paddingHorizontal: 16,
    paddingVertical: 18
  },
  walletDarkLabel: { color: "rgba(255,255,255,0.6)", fontSize: 11, fontWeight: "600" },
  walletDarkAmount: { color: color.white, fontSize: 24, fontWeight: "900", marginTop: 4 },
  walletDarkHint: { color: "rgba(255,255,255,0.45)", fontSize: 11, marginTop: 4 },
  walletCard: {
    backgroundColor: color.white,
    borderColor: color.line,
    borderRadius: 14,
    borderWidth: 1,
    marginBottom: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    ...shadows.card
  },
  walletCardLabel: { color: color.ink, fontSize: 11, fontWeight: "700" },
  walletCardValue: { color: color.ink, fontSize: 16, fontWeight: "800", marginTop: 4 },
  walletCardHint: { color: color.muted, fontSize: 11, lineHeight: 15, marginTop: 4 },
  walletAction: {
    alignItems: "center",
    backgroundColor: color.white,
    borderColor: color.line,
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: "row",
    gap: 10,
    marginBottom: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    ...shadows.card
  },
  walletActionIcon: { backgroundColor: "#F5F1F7", borderRadius: 10, fontSize: 16, height: 36, textAlign: "center", lineHeight: 36, width: 36 },
  walletActionBody: { flex: 1 },
  walletActionLabel: { color: color.ink, fontSize: 11, fontWeight: "700" },
  walletActionDesc: { color: color.muted, fontSize: 11, marginTop: 2 },
  walletActionArrow: { color: color.muted, fontSize: 16 },
  walletBtnLight: {
    alignItems: "center",
    borderColor: color.line,
    borderRadius: 999,
    borderWidth: 1,
    marginTop: 4,
    paddingVertical: 11
  },
  walletBtnLightText: { color: color.ink, fontSize: 11, fontWeight: "700" },

  subSection: {
    backgroundColor: color.white,
    borderColor: "rgba(20,18,31,0.04)",
    borderRadius: 17,
    borderWidth: 1,
    marginBottom: 10,
    overflow: "hidden",
    ...shadows.card
  },
  subSectionTitle: {
    backgroundColor: color.surface,
    borderBottomColor: color.line,
    borderBottomWidth: 1,
    color: color.muted,
    fontSize: 11,
    fontWeight: "700",
    paddingHorizontal: 12,
    paddingVertical: 6
  },
  customSectionTitle: { color: color.ink, fontSize: 11, fontWeight: "700", marginTop: 10 },
  customSectionHint: { color: color.muted, fontSize: 11, marginBottom: 2, marginTop: 1 },
  subRow: {
    borderBottomColor: color.line,
    borderBottomWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 12,
    paddingVertical: 10
  },
  subRowLabel: { color: color.ink, fontSize: 11, fontWeight: "600", flex: 1 },
  subRowValue: { color: color.muted, fontSize: 11, flex: 1, textAlign: "right" },

  memorySection: { marginTop: 13 },
  memorySectionHead: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 5,
    paddingHorizontal: 2
  },
  memorySectionTitle: { color: color.ink, fontSize: 11, fontWeight: "700" },
  memorySectionCount: { color: color.muted, fontSize: 11 },
  memoryCard: {
    backgroundColor: color.white,
    borderColor: "rgba(20,18,31,0.04)",
    borderRadius: 17,
    borderWidth: 1,
    marginBottom: 6,
    padding: 12,
    ...shadows.card
  },
  memoryCardBody: {
    alignItems: "center",
    flexDirection: "row"
  },
  memoryCardLeft: { flex: 1 },
  memoryLabel: { color: color.ink, fontSize: 11, fontWeight: "800", marginBottom: 4 },
  memoryValue: { color: color.ink, fontSize: 12, lineHeight: 17, fontWeight: "700" },
  memorySource: { color: "#8B8292", fontSize: 11, marginTop: 6, lineHeight: 15 },
  memoryCardRight: { alignItems: "center", flexDirection: "row", gap: 4 },
  memoryStatusConfirmed: {
    backgroundColor: "#EEF8D6",
    borderRadius: 999,
    paddingHorizontal: 7,
    paddingVertical: 4
  },
  memoryStatusText: { color: "#506900", fontSize: 11, fontWeight: "900" },
  memoryStatusSuggested: {
    backgroundColor: "#F1E8FF",
    borderRadius: 999,
    paddingHorizontal: 7,
    paddingVertical: 4
  },
  memoryStatusTextSuggested: { color: "#6330B2", fontSize: 11, fontWeight: "900" },
  memoryChev: { color: "#B0A8B5", fontSize: 18 },
  memoryDarkCard: {
    backgroundColor: color.ink,
    borderRadius: 16,
    marginBottom: 10,
    padding: 12
  },
  memoryDarkTitle: { color: color.white, fontSize: 11, fontWeight: "700" },
  memoryDarkBody: { color: "rgba(255,255,255,0.7)", fontSize: 11, lineHeight: 15, marginTop: 4 },
  memoryBtnLight: {
    backgroundColor: color.white,
    borderColor: color.line,
    borderRadius: 12,
    borderWidth: 1,
    marginBottom: 6,
    paddingVertical: 10,
    alignItems: "center"
  },
  memoryBtnLightText: { color: color.ink, fontSize: 11, fontWeight: "700" },

  fakeQr: {
    alignContent: "flex-start",
    backgroundColor: color.white,
    borderColor: "#EAE5ED",
    borderRadius: 6,
    borderWidth: 1,
    flexDirection: "row",
    flexWrap: "wrap",
    ...shadows.card
  },
  fakeQrCell: { backgroundColor: "transparent", borderRadius: 1 },
  fakeQrCellOn: { backgroundColor: "#17131F" },

  qrCard: {
    alignItems: "center",
    backgroundColor: color.white,
    borderColor: "rgba(20,18,31,0.04)",
    borderRadius: 17,
    borderWidth: 1,
    flexDirection: "row",
    gap: 13,
    marginVertical: 8,
    padding: 12,
    ...shadows.card
  },
  qrCardCenter: { flexDirection: "column" },
  qrCardText: { flex: 1 },
  qrCardTextCenter: { alignItems: "center", flex: 1, width: "100%" },
  qrCardTitle: { color: color.ink, fontSize: 11, fontWeight: "800" },
  qrCardDesc: { color: color.muted, fontSize: 11, lineHeight: 15, marginVertical: 4 },
  qrCardBtn: {
    alignSelf: "flex-start",
    backgroundColor: color.ink,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 7
  },
  qrCardBtnText: { color: color.white, fontSize: 11, fontWeight: "900" },
  // PROFILE-QR-004：二维码卡片的多动作行（复制 / 保存到相册 / 打开二维码页）。
  qrCardActions: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 6 },
  qrCardBtnGhost: {
    alignSelf: "flex-start",
    backgroundColor: "rgba(20,18,31,0.05)",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 7
  },
  qrCardBtnTextGhost: { color: color.ink, fontSize: 11, fontWeight: "800" },
  qrCardNotice: { color: color.muted, fontSize: 11, marginTop: 6 },

  // STORE-REC/PROFILE-QR-001: 真实个人二维码（渲染见 components/proxy-qr-code）。
  qrRealCard: {
    alignItems: "center",
    backgroundColor: color.white,
    borderColor: "rgba(20,18,31,0.04)",
    borderRadius: 17,
    borderWidth: 1,
    marginVertical: 8,
    padding: 18,
    ...shadows.card
  },
  qrRealHandle: { color: color.ink, fontSize: 13, fontWeight: "800", marginTop: 12 },
  qrRealHint: { color: color.muted, fontSize: 11, marginTop: 4, textAlign: "center" },
  qrRealActions: { flexDirection: "row", gap: 8, marginTop: 14, width: "100%" },
  qrRealBtn: {
    alignItems: "center",
    backgroundColor: color.ink,
    borderRadius: 999,
    flex: 1,
    paddingVertical: 10
  },
  qrRealBtnGhost: {
    alignItems: "center",
    backgroundColor: color.white,
    borderColor: color.line,
    borderRadius: 999,
    borderWidth: 1,
    flex: 1,
    paddingVertical: 10
  },
  qrRealBtnText: { color: color.white, fontSize: 12, fontWeight: "800" },
  qrRealBtnTextGhost: { color: color.ink, fontSize: 12, fontWeight: "800" },
  qrRealNotice: { color: "#1B7F4D", fontSize: 11, marginTop: 8, textAlign: "center" },
  // PROFILE-QR-002：被分享出去的二维码图取自这块白底（quiet zone 留足，纯白高对比）。
  qrShotWrap: { alignItems: "center", backgroundColor: color.white, padding: 12 },

  socialRow: {
    alignItems: "center",
    backgroundColor: color.white,
    borderColor: "rgba(20,18,31,0.04)",
    borderRadius: 15,
    borderWidth: 1,
    flexDirection: "row",
    gap: 9,
    marginVertical: 6,
    padding: 11
  },
  socialRowIcon: {
    alignItems: "center",
    backgroundColor: "#F5F1F8",
    borderRadius: 10,
    height: 31,
    justifyContent: "center",
    width: 31
  },
  socialRowIconText: { color: "#6F37B9", fontSize: 11, fontWeight: "900" },
  socialRowCopy: { flex: 1 },
  socialRowLabel: { color: color.ink, fontSize: 11, fontWeight: "800" },
  socialRowDesc: { color: color.muted, fontSize: 11, lineHeight: 15, marginTop: 2 },
  socialRowChev: { color: "#A59EAA", fontSize: 15 },

  heroCard: {
    backgroundColor: color.white,
    borderColor: "rgba(20,18,31,0.04)",
    borderRadius: 17,
    borderWidth: 1,
    marginVertical: 8,
    padding: 13,
    ...shadows.card
  },
  heroTop: { alignItems: "center", flexDirection: "row", gap: 10 },
  heroAvatar: {
    alignItems: "center",
    borderRadius: 15,
    height: 46,
    justifyContent: "center",
    width: 46
  },
  heroAvatarText: { color: color.white, fontSize: 18, fontWeight: "900" },
  heroCopy: { flex: 1 },
  heroName: { color: color.ink, fontSize: 14, fontWeight: "800" },
  heroMeta: { color: color.muted, fontSize: 11, marginTop: 3 },
  heroStatus: {
    backgroundColor: "#EEF8D6",
    borderColor: "#DFEBC7",
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 9,
    paddingVertical: 6
  },
  heroStatusText: { color: "#465C00", fontSize: 11, fontWeight: "900" },
  availabilityOverlay: { backgroundColor: "rgba(20,18,31,0.46)", flex: 1, justifyContent: "flex-end", padding: 12 },
  availabilitySheet: { backgroundColor: color.white, borderRadius: 25, padding: 19 },
  availabilityTitle: { color: color.ink, fontSize: 16, fontWeight: "800" },
  availabilitySub: { color: color.muted, fontSize: 11, lineHeight: 15, marginBottom: 12, marginTop: 4 },
  availabilityOption: { alignItems: "center", backgroundColor: color.white, borderColor: color.line, borderRadius: 16, borderWidth: 1, flexDirection: "row", gap: 10, marginBottom: 8, padding: 11 },
  availabilityOptionActive: { backgroundColor: "#FAF8FB", borderColor: color.ink, borderWidth: 1.5 },
  availabilityMark: { alignItems: "center", backgroundColor: "#F2EDF5", borderRadius: 13, height: 40, justifyContent: "center", width: 40 },
  availabilityMarkActive: { backgroundColor: color.ink },
  availabilityCopy: { flex: 1 },
  availabilityOptionTitle: { color: color.ink, fontSize: 11, fontWeight: "800" },
  availabilityOptionDesc: { color: color.muted, fontSize: 11, lineHeight: 15, marginTop: 3 },
  availabilityAction: { color: "#62586A", fontSize: 11, fontWeight: "900" },
  trustStrip: {
    flexDirection: "row",
    gap: 6,
    marginTop: 11
  },
  trustStripItem: {
    alignItems: "center",
    backgroundColor: "#F8F6FA",
    borderRadius: 11,
    flex: 1,
    paddingVertical: 8
  },
  trustStripValue: { color: color.ink, fontSize: 12, fontWeight: "800" },
  trustStripLabel: { color: color.muted, fontSize: 11, marginTop: 2 },

  personalHubContent: { paddingBottom: 0 },
  personalTopbar: {
    alignItems: "center",
    flexDirection: "row",
    height: 46,
    paddingHorizontal: 18,
    paddingTop: 7
  },
  personalTopbarButton: { alignItems: "center", height: 34, justifyContent: "center", width: 34 },
  personalTopbarIcon: { color: color.ink, fontSize: 21, fontWeight: "300", lineHeight: 24 },
  personalTopbarHandle: { color: color.ink, flex: 1, fontSize: 15, fontWeight: "700", overflow: "hidden", textAlign: "left", marginLeft: 4 },
  personalTopbarTools: { flexDirection: "row", gap: 5 },
  personalTopbarIconBtn: { width: 34, height: 34, alignItems: "center", justifyContent: "center" },

  personalHead: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 16, paddingHorizontal: 18, paddingTop: 7 },
  personalNameBlock: { flex: 1, minWidth: 0 },
  personalName: { color: color.ink, fontSize: 24, fontWeight: "800", letterSpacing: -0.96, lineHeight: 28 },
  personalHandleSub: { color: "#444", fontSize: 11, marginTop: 4 },
  personalAvaWrap: { position: "relative", width: 82, height: 82, justifyContent: "flex-end" },
  personalAva: { width: 82, height: 82, borderRadius: 41, backgroundColor: "#111", alignItems: "center", justifyContent: "center", overflow: "hidden", borderWidth: 1, borderColor: "#ececec" },
  personalAvaLetter: { color: color.white, fontSize: 27, fontWeight: "800" },
  personalAvaAdd: {
    position: "absolute", left: -6, bottom: -2, width: 32, height: 32, borderRadius: 16,
    borderWidth: 3, borderColor: "#fff", backgroundColor: "#fff",
    alignItems: "center", justifyContent: "center"
  },

  personalIntroRow: { alignItems: "center", flexDirection: "row", gap: 12, paddingHorizontal: 18, paddingTop: 10 },
  personalIntroText: { color: color.ink, flex: 1, fontSize: 11, lineHeight: 16 },
  personalBio: { paddingHorizontal: 18, marginTop: 13 },
  personalBioText: { color: color.ink, fontSize: 11, lineHeight: 16 },
  personalLinkRow: { flexDirection: "row", alignItems: "center", gap: 5, marginTop: 8 },
  personalLinkText: { color: "#333", fontSize: 11, fontWeight: "600" },

  personalTopics: { flexDirection: "row", gap: 6, flexWrap: "wrap", marginTop: 11 },
  personalTopicPill: { borderWidth: 1, borderColor: "#e1e1e1", backgroundColor: "#fff", borderRadius: 999, paddingHorizontal: 10, paddingVertical: 6 },
  personalTopicText: { color: "#333", fontSize: 11, fontWeight: "600" },

  personalStatRow: { alignItems: "center", flexDirection: "row", justifyContent: "space-between", marginBottom: 15, marginTop: 12 },
  personalStatText: { color: "#8c8c8c", fontSize: 11 },
  personalStatValue: { color: "#111", fontWeight: "800" },

  personalFollowersCount: { color: "#7f7f7f", fontSize: 11 },
  personalFollowersValue: { color: "#111", fontWeight: "800" },
  personalActions: { flexDirection: "row", gap: 8, marginTop: 16 },
  personalActionButton: { alignItems: "center", backgroundColor: color.white, borderColor: "#D7D7D7", borderRadius: 10, borderWidth: 1, flex: 1, height: 38, justifyContent: "center" },
  personalActionText: { color: color.ink, fontSize: 13, fontWeight: "700" },
  personalActionPrimary: { backgroundColor: "#111", borderColor: "#111" },
  personalActionPrimaryText: { color: color.white, fontSize: 13, fontWeight: "700" },
  personalActionLime: { backgroundColor: "#C9FF08", borderColor: "#C9FF08" },
  personalActionLimeText: { color: color.ink, fontSize: 13, fontWeight: "700" },
  personalTabs: { backgroundColor: color.white, borderBottomColor: "#E8E8E8", borderBottomWidth: 1, flexDirection: "row", height: 47, position: "relative", top: 0, zIndex: 18 },
  personalTab: { alignItems: "center", flex: 1, height: 47, justifyContent: "center", position: "relative" },
  personalTabUnderline: { backgroundColor: "#111", bottom: -1, height: 1.5, left: "16%", position: "absolute", right: "16%" },
  personalTabText: { color: "#8A8A8A", fontSize: 13, fontWeight: "600" },
  personalTabTextActive: { color: color.ink, fontWeight: "700" },
  personalPost: { borderBottomColor: "#E8E8E8", borderBottomWidth: 1, paddingBottom: 14, paddingHorizontal: 18, paddingTop: 16 },
  personalPostHead: { alignItems: "flex-start", flexDirection: "row", gap: 10 },
  personalPostAvatar: { alignItems: "center", backgroundColor: "#111", borderRadius: 19, color: color.white, fontSize: 14, fontWeight: "700", height: 38, justifyContent: "center", overflow: "hidden", width: 38 },
  personalPostAvatarText: { color: color.white, fontSize: 14, fontWeight: "700" },
  personalPostAvatarImage: { borderRadius: 19, height: 38, width: 38 },
  personalPostBody: { flex: 1, marginTop: -12, paddingLeft: 48 },
  personalPostNameLine: { alignItems: "center", flexDirection: "row", gap: 6, minWidth: 0 },
  personalPostName: { color: color.ink, fontSize: 13, fontWeight: "700" },
  personalPostTime: { color: "#777", fontSize: 11, lineHeight: 14 },
  personalPostMenu: { alignItems: "center", height: 28, justifyContent: "center", width: 32 },
  personalPostMenuText: { color: "#555", fontSize: 19, lineHeight: 22 },
  personalPostText: { color: color.ink, fontSize: 14, lineHeight: 21, marginTop: 5 },
  personalPostContext: { alignItems: "center", color: "#666", flexDirection: "row", flexWrap: "wrap", fontSize: 11, gap: 7, marginTop: 9 },
  personalPostSceneChip: { backgroundColor: color.white, borderColor: "#DDD", borderRadius: 999, borderWidth: 1, color: color.ink, fontSize: 11, fontWeight: "600", paddingHorizontal: 8, paddingVertical: 4 },
  personalPostActions: { flexDirection: "row", gap: 20, marginTop: 12 },
  personalPostAction: { color: "#666", fontSize: 12, fontWeight: "500" },
  personalPostOwnerMenu: { flexDirection: "row", gap: 10, marginTop: 10 },
  personalPostOwnerItem: { color: "#777", fontSize: 11, fontWeight: "600" },
  personalPostOwnerDanger: { color: "#E5484D", fontSize: 11, fontWeight: "600" },
  personalPostOwnerBadge: { color: "#777", fontSize: 11, fontWeight: "500" },
  personalEmpty: { color: "#777", fontSize: 12, lineHeight: 18, paddingHorizontal: 32, paddingVertical: 58, textAlign: "center" },
  personalEmptyTitle: { color: color.ink, fontSize: 16, fontWeight: "700", marginBottom: 7 },
  personalPhotoGrid: { backgroundColor: color.white, flexDirection: "row", flexWrap: "wrap", padding: 1 },
  personalPhotoTile: { aspectRatio: 1, backgroundColor: "#EEE", flexBasis: "33.333%", overflow: "hidden", padding: 0, position: "relative" },
  personalPhotoImage: { height: "100%", width: "100%" },
  personalPhotoPrivate: { backgroundColor: "rgba(0,0,0,.65)", borderRadius: 999, color: color.white, fontSize: 11, fontWeight: "700", paddingHorizontal: 5, paddingVertical: 3, position: "absolute", right: 5, top: 5 },
  personalRecords: { },
  personalRecordRow: { alignItems: "center", borderBottomColor: "#E8E8E8", borderBottomWidth: 1, flexDirection: "row", gap: 11, paddingHorizontal: 18, paddingVertical: 15 },
  personalRecordIcon: { alignItems: "center", backgroundColor: "#F5F5F5", borderRadius: 20, color: color.ink, fontSize: 14, fontWeight: "700", height: 40, justifyContent: "center", width: 40 },
  personalRecordCopy: { flex: 1 },
  personalRecordTitle: { color: color.ink, fontSize: 13, fontWeight: "700" },
  personalRecordDesc: { color: "#777", fontSize: 11, lineHeight: 14, marginTop: 4 },
  personalRecordValue: { color: color.ink, fontSize: 12, fontWeight: "700" },
  profileEditorOverlay: { backgroundColor: "rgba(20,18,31,0.42)", flex: 1, justifyContent: "flex-end" },
  profileEditorSheet: { backgroundColor: color.white, borderTopLeftRadius: 24, borderTopRightRadius: 24, paddingBottom: 30, paddingHorizontal: 20, paddingTop: 18 },
  profileEditorHead: { alignItems: "center", flexDirection: "row", justifyContent: "space-between", marginBottom: 10 },
  profileEditorTitle: { color: color.ink, fontSize: 18, fontWeight: "900" },
  profileEditorDone: { color: "#FF0A6C", fontSize: 14, fontWeight: "800" },
  profileEditorAvatarRow: { alignItems: "center", flexDirection: "row", gap: 12, paddingBottom: 10, paddingTop: 4 },
  profileEditorAvatar: { borderRadius: 26, height: 52, width: 52 },
  profileEditorAvatarTitle: { color: color.ink, fontSize: 14, fontWeight: "800" },
  profileEditorAvatarHint: { color: color.muted, fontSize: 11, marginTop: 3 },
  profileEditorField: { borderBottomColor: "#ECE8EF", borderBottomWidth: 1, paddingVertical: 10 },
  profileEditorLabel: { color: color.muted, fontSize: 11, fontWeight: "700" },
  profileEditorInput: { color: color.ink, fontSize: 14, paddingHorizontal: 0, paddingVertical: 7 },

  sheetOverlay: { backgroundColor: "rgba(20,18,31,0.42)", flex: 1, justifyContent: "flex-end", padding: 12 },
  sheetCard: { backgroundColor: color.white, borderRadius: 22, maxHeight: "72%", padding: 17 },
  sheetTitle: { color: color.ink, fontSize: 15, fontWeight: "800", marginBottom: 4 },
  sheetSub: { color: color.muted, fontSize: 11, marginBottom: 12 },
  sheetField: { borderColor: "#e6e6e6", borderRadius: 12, borderWidth: 1, padding: 9, marginVertical: 8 },
  sheetFieldLabel: { color: color.muted, fontSize: 11, fontWeight: "700" },
  sheetFieldValue: { color: color.ink, fontSize: 15, fontWeight: "800", marginTop: 4 },
  sheetFieldInput: { color: color.ink, fontSize: 11, marginTop: 4, padding: 0 },
  sheetWideBtn: { alignItems: "center", backgroundColor: color.white, borderColor: "#ddd", borderRadius: 11, borderWidth: 1, height: 38, justifyContent: "center", marginTop: 7, width: "100%" },
  sheetWideBtnDark: { backgroundColor: "#111", borderColor: "#111" },
  sheetWideBtnText: { color: color.ink, fontSize: 11, fontWeight: "800" },
  sheetWideBtnTextDark: { color: color.white, fontSize: 11, fontWeight: "800" },

  abilitySheetHead: { alignItems: "center", flexDirection: "row", gap: 9, marginBottom: 6 },
  abilityHead: { alignItems: "center", flexDirection: "row", gap: 8, marginBottom: 6 },
  abilityIcon: {
    alignItems: "center",
    backgroundColor: "#F5F1F8",
    borderRadius: 10,
    height: 30,
    justifyContent: "center",
    width: 30
  },
  abilityIconText: { color: "#6F37B9", fontSize: 13, fontWeight: "900" },
  abilitySub: { color: color.muted, fontSize: 11, marginTop: 1 },
  abilityNote: { color: color.muted, fontSize: 11, lineHeight: 15, marginTop: 4 },
  abilityFieldBlock: { marginTop: 8 },
  abilityFieldLabel: { color: color.muted, fontSize: 11, fontWeight: "700", marginBottom: 4 },

  chipWrap: { flexDirection: "row", flexWrap: "wrap", gap: 6 },
  chip: {
    backgroundColor: "#F8F6FA",
    borderColor: "#EAE5ED",
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 6
  },
  chipActive: { backgroundColor: color.ink, borderColor: color.ink },
  chipText: { color: color.ink, fontSize: 11, fontWeight: "700" },
  chipTextActive: { color: color.white, fontSize: 11, fontWeight: "800" },
  dayCell: {
    alignItems: "center",
    backgroundColor: "#F8F6FA",
    borderColor: "#EAE5ED",
    borderRadius: 10,
    borderWidth: 1,
    flex: 1,
    paddingVertical: 8
  },

  avDayRow: {
    alignItems: "center",
    borderBottomColor: "#F1EDF3",
    borderBottomWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 7
  },
  avDayRowDate: { color: color.ink, fontSize: 11, fontWeight: "700" },
  avDayRowState: { color: "#4A5568", fontSize: 11, fontWeight: "600" },
  avDayRowOff: { color: "#A59EAA" },
  avCalendar: { flexDirection: "row", flexWrap: "wrap", gap: 5, marginVertical: 8 },
  avCell: {
    alignItems: "center",
    backgroundColor: "#FDFCFE",
    borderColor: "#EFEAF2",
    borderRadius: 10,
    borderWidth: 1,
    paddingVertical: 5,
    width: "18%"
  },
  avCell_base: { backgroundColor: "#F3FBFF", borderColor: "#CBE9F7" },
  avCell_full: { backgroundColor: "#EEF8D6", borderColor: "#DFEBC7" },
  avCell_off: { backgroundColor: "#F6EEF0", borderColor: "#EBD9DD" },
  avCell_custom: { backgroundColor: "#F6F1FC", borderColor: "#E2D4F4" },
  avCell_blank: { backgroundColor: "#FAF9FB" },
  avCellDay: { color: color.ink, fontSize: 11, fontWeight: "800" },
  avCellWeek: { color: "#A59EAA", fontSize: 11 },
  avCellValue: { color: "#22506E", fontSize: 11, fontWeight: "800", marginTop: 1 },
  avCellValueMuted: { color: "#B9B3BD" },

  availabilityLead: { color: color.muted, fontSize: 13, lineHeight: 19, marginBottom: 14, marginTop: 5 },
  availabilitySummaryCard: { alignItems: "center", backgroundColor: color.white, borderColor: color.line, borderRadius: 20, borderWidth: 1, flexDirection: "row", gap: 12, marginBottom: 18, padding: 14, ...shadows.card },
  availabilityRuleCard: { alignItems: "center", backgroundColor: color.white, borderColor: color.line, borderRadius: 20, borderWidth: 1, flexDirection: "row", gap: 12, marginBottom: 12, padding: 15, ...shadows.card },
  availabilityRuleIcon: { alignItems: "center", backgroundColor: color.lime, borderRadius: 14, height: 46, justifyContent: "center", width: 46 },
  availabilityRuleCopy: { flex: 1 },
  availabilityRuleKicker: { color: color.muted, fontSize: 11, fontWeight: "700" },
  availabilityRuleValue: { color: color.ink, fontSize: 16, fontWeight: "900", marginTop: 3 },
  availabilityEditButton: { backgroundColor: color.white, borderColor: color.line, borderRadius: 12, borderWidth: 1, paddingHorizontal: 12, paddingVertical: 8 },
  availabilityEditText: { color: color.ink, fontSize: 12, fontWeight: "800" },
  abilityCompactCard: { backgroundColor: color.white, borderColor: color.line, borderRadius: 20, borderWidth: 1, marginBottom: 10, padding: 14, ...shadows.card },
  abilityFieldChips: { flexDirection: "row", flexWrap: "wrap", gap: 7, marginTop: 11 },
  abilityFieldChip: { backgroundColor: "#F7F3F9", borderRadius: 999, paddingHorizontal: 10, paddingVertical: 7 },
  abilityFieldChipText: { color: "#514957", fontSize: 11, fontWeight: "600" },
  abilityFieldChipLabel: { color: color.ink, fontWeight: "800" },
  addAbilityRow: { flexDirection: "row", gap: 8, marginBottom: 18, marginTop: 2 },
  addAbilityChip: { alignItems: "center", backgroundColor: color.white, borderColor: color.line, borderRadius: 14, borderWidth: 1, flex: 1, paddingVertical: 11 },
  addAbilityChipText: { color: color.ink, fontSize: 12, fontWeight: "800" },
  availabilityMonthCard: { backgroundColor: color.white, borderColor: color.line, borderRadius: 22, borderWidth: 1, padding: 14, ...shadows.card },
  availabilityMonthHead: { alignItems: "center", flexDirection: "row", justifyContent: "space-between", marginBottom: 12 },
  availabilityMonthTitle: { color: color.ink, fontSize: 16, fontWeight: "900" },
  availabilityClear: { color: color.muted, fontSize: 11, fontWeight: "800" },
  availabilityWeekHead: { flexDirection: "row", marginBottom: 5 },
  availabilityWeekName: { color: "#9C96A0", fontSize: 11, fontWeight: "800", textAlign: "center", width: "14.285%" },
  availabilityMonthGrid: { flexDirection: "row", flexWrap: "wrap" },
  availabilityMonthBlank: { aspectRatio: 1, width: "14.285%" },
  availabilityMonthDay: { alignItems: "center", aspectRatio: 1, backgroundColor: color.white, borderColor: "#EEE9F0", borderRadius: 11, borderWidth: 1, justifyContent: "center", marginBottom: 5, transform: [{ scale: 0.92 }], width: "14.285%" },
  availabilityMonthDay_base: { backgroundColor: color.white },
  availabilityMonthDay_full: { backgroundColor: color.lime, borderColor: color.lime },
  availabilityMonthDay_off: { backgroundColor: "#F1EFF2", borderColor: "#F1EFF2" },
  availabilityMonthDay_custom: { borderColor: color.ink, borderWidth: 2 },
  availabilityMonthDay_blank: { backgroundColor: "#FAF9FB" },
  availabilityMonthNumber: { color: color.ink, fontSize: 13, fontWeight: "900" },
  availabilityMonthNumberOff: { color: "#AAA4AD" },
  availabilityBaseDot: { backgroundColor: color.lime, borderRadius: 3, height: 6, marginTop: 4, width: 6 },
  availabilityOffMark: { bottom: 1, color: "#8D8792", fontSize: 11, fontWeight: "900", position: "absolute" },
  availabilityLegend: { flexDirection: "row", flexWrap: "wrap", gap: 10, marginTop: 10 },
  availabilityLegendText: { color: color.muted, fontSize: 11, fontWeight: "700" },

  privacyLadder: {
    backgroundColor: color.white,
    borderColor: "rgba(20,18,31,0.04)",
    borderRadius: 17,
    borderWidth: 1,
    marginVertical: 8,
    padding: 11,
    ...shadows.card
  },
  privacyStep: {
    alignItems: "center",
    borderBottomColor: "#F1EDF3",
    borderBottomWidth: 1,
    flexDirection: "row",
    gap: 8,
    paddingVertical: 9
  },
  privacyStepIndex: {
    alignItems: "center",
    backgroundColor: "#F5F1F8",
    borderRadius: 8,
    height: 24,
    justifyContent: "center",
    width: 24
  },
  privacyStepIndexText: { color: "#6C3CB3", fontSize: 11, fontWeight: "900" },
  privacyStepCopy: { flex: 1 },
  privacyStepTitle: { color: color.ink, fontSize: 11, fontWeight: "700" },
  privacyStepDesc: { color: color.muted, fontSize: 11, marginTop: 2 },
  privacyStepTag: {
    backgroundColor: "#F7F4F9",
    borderRadius: 999,
    paddingHorizontal: 6,
    paddingVertical: 4
  },
  privacyStepTagText: { color: "#716879", fontSize: 11, fontWeight: "800" },

  storeTop: {
    backgroundColor: color.ink,
    borderRadius: 17,
    marginVertical: 8,
    padding: 14
  },
  storeTopRow: { alignItems: "center", flexDirection: "row", gap: 10 },
  storeAvatar: {
    alignItems: "center",
    borderRadius: 15,
    height: 46,
    justifyContent: "center",
    width: 46
  },
  storeAvatarText: { color: color.white, fontSize: 20, fontWeight: "900" },
  storeStats: {
    flexDirection: "row",
    gap: 6,
    marginTop: 12
  },
  storeStatItem: {
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.08)",
    borderRadius: 11,
    flex: 1,
    paddingVertical: 8
  },
  storeStatValue: { color: color.white, fontSize: 12, fontWeight: "800" },
  storeStatLabel: { color: "rgba(255,255,255,0.6)", fontSize: 11, marginTop: 2 },

  bizGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginVertical: 4
  },
  bizTile: {
    backgroundColor: color.white,
    borderColor: "rgba(20,18,31,0.04)",
    borderRadius: 14,
    borderWidth: 1,
    padding: 11,
    width: "48%"
  },
  bizTileIcon: {
    alignItems: "center",
    backgroundColor: "#F5F1F8",
    borderRadius: 9,
    height: 30,
    justifyContent: "center",
    width: 30
  },
  bizTileIconText: { color: "#6F37B9", fontSize: 12, fontWeight: "900" },
  bizTileLabel: { color: color.ink, fontSize: 11, fontWeight: "800", marginTop: 7 },
  bizTileDesc: { color: color.muted, fontSize: 11, lineHeight: 15, marginTop: 2 },

  offerCard: {
    backgroundColor: color.white,
    borderColor: "rgba(20,18,31,0.04)",
    borderRadius: 15,
    borderWidth: 1,
    marginVertical: 5,
    padding: 11,
    ...shadows.card
  },
  offerTitle: { color: color.ink, fontSize: 11, fontWeight: "800" },
  offerMeta: { color: color.muted, fontSize: 11, marginTop: 3 },
  // BADGE-WALL-001: 徽章墙。得过的正常显示，没得过的整块降透明度 + 给出来条件。
  badgeWall: { marginTop: 14, paddingHorizontal: 18 },
  badgeWallTitle: { color: color.ink, fontSize: 14, fontWeight: "900" },
  badgeWallLoading: { color: color.muted, fontSize: 12, marginTop: 8 },
  badgeWallFailed: { alignItems: "center", backgroundColor: color.white, borderColor: color.line, borderRadius: 14, borderWidth: 1, flexDirection: "row", justifyContent: "space-between", marginTop: 8, padding: 12 },
  badgeWallFailedText: { color: color.error, flex: 1, fontSize: 12, fontWeight: "700" },
  badgeWallRetry: { backgroundColor: color.ink, borderRadius: 9, paddingHorizontal: 12, paddingVertical: 7 },
  badgeWallRetryText: { color: color.white, fontSize: 11, fontWeight: "800" },
  badgeGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 10 },
  badgeTile: { alignItems: "center", backgroundColor: color.white, borderColor: color.line, borderRadius: 14, borderWidth: 1, paddingVertical: 10, width: "31%" },
  badgeTileLocked: { opacity: 0.55 },
  badgeIcon: { fontSize: 24 },
  badgeName: { color: color.ink, fontSize: 11, fontWeight: "800", marginTop: 4, textAlign: "center" },
  badgeDesc: { color: color.muted, fontSize: 11, lineHeight: 14, marginTop: 3, textAlign: "center" },
  badgeProgress: { color: color.violet, fontSize: 11, fontWeight: "800", marginTop: 3 },
});
