package media

import (
	"bufio"
	"bytes"
	"context"
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"io"
	"log"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/proxy-app/proxy-api/internal/clock"
	"github.com/proxy-app/proxy-api/internal/command"
	"github.com/proxy-app/proxy-api/internal/event"
	"github.com/proxy-app/proxy-api/internal/aipersona"
)

// Media P0（PRD Chapter06A §9-12）。
// 普通视频：upload / thumbnail / play / pause / seek / fullscreen / caption / share。
// 只有 READY 的视频允许正式播放。
// FFmpeg 不是播放器：客户端播 MP4/HLS URL；FFmpeg 负责把用户上传的
// HEVC/MOV/奇怪 rotation/不同音频 codec 标准化为 H.264+AAC MP4+faststart。
// 不做：多码率 HLS / ABR / 转码集群 / 直播 / WebRTC（P0 只要求正常播放）。

// MediaAsset 是媒体资产（IMAGE | VIDEO | AUDIO）。
type MediaAsset struct {
	MediaAssetID        string    `json:"mediaAssetId"`
	OwnerPrincipalType  string    `json:"ownerPrincipalType"`
	OwnerPrincipalID    string    `json:"ownerPrincipalId"`
	MediaType           string    `json:"mediaType"` // IMAGE | VIDEO | AUDIO
	OriginalStorageKey  string    `json:"originalStorageKey"`
	PlaybackStorageKey  string    `json:"playbackStorageKey,omitempty"`
	ThumbnailStorageKey string    `json:"thumbnailStorageKey,omitempty"`
	MimeType            string    `json:"mimeType,omitempty"`
	Width               int       `json:"width,omitempty"`
	Height              int       `json:"height,omitempty"`
	DurationMs          int64     `json:"durationMs,omitempty"`
	Codec               string    `json:"codec,omitempty"`
	ProcessingStatus    string    `json:"processingStatus"` // UPLOADING | PROCESSING | READY | FAILED
	PlaybackURL         string    `json:"playbackUrl,omitempty"`
	ThumbnailURL        string    `json:"thumbnailUrl,omitempty"`
	SourceBytes         int64     `json:"sourceBytes,omitempty"`
	ChecksumSHA256      string    `json:"checksumSha256,omitempty"`
	Orientation         int       `json:"orientation,omitempty"`
	ColorSpace          string    `json:"colorSpace,omitempty"`
	HasAlpha            bool      `json:"hasAlpha"`
	Animated            bool      `json:"animated"`
	ModerationStatus    string    `json:"moderationStatus"`
	VisibilityClass     string    `json:"visibilityClass"`
	// CompositionHint：主体类型 + 关键区域。P0 worker 可空，前端低置信度回落。
	CompositionHint           *MediaCompositionHint `json:"compositionHint,omitempty"`
	CompositionRecipeVersion  string                `json:"compositionRecipeVersion,omitempty"`
	CompositionComputedAt     *time.Time            `json:"compositionComputedAt,omitempty"`
	CompositionConfidence     float64               `json:"compositionConfidence,omitempty"`
	// DominantColorHex 主色（#RRGGBB），worker v1 派生后填。contain 模式下客户端
	// 用此色当 frame 背景，替代写死深紫黑 → 消除"图浅/背景深"的强对比灰边。
	// 失败填 DefaultDominantColor（#0E0A14）兑底。
	DominantColorHex string `json:"dominantColorHex,omitempty"`
	CreatedAt           time.Time `json:"createdAt"`
	UpdatedAt           time.Time `json:"updatedAt"`
	// LastError：确定性拒绝原因（如音频超 30s）。仅 FAILED 资产携带，供客户端展示。
	LastError string `json:"lastError,omitempty"`
	// R16.7-P1-K (LC-06) + R16.7-P1-I (LC-07): AI generation
	// provenance. AIGenerationSource is the single source of
	// truth for 'is this asset AI-generated?'; the boolean
	// AIGenerated is the convenience view. PRD v1.4 §4
	// (Vietnam 134/2025/QH15 Art. 12) requires every
	// AI-generated media asset to carry this label; the
	// platform must fail closed (refuse to publish) when the
	// source cannot be determined. The MarkMediaReady
	// handler is the gate.
	//
	// Source values:
	//   USER_UPLOADED  — captured by the device, no AI in the
	//                    loop. AIGenerated is false.
	//   AI_PERSONA     — produced by an AI persona
	//                    (aipersona.PersonaTypeUserTwin /
	//                    Creative). PersonaID and SubjectID
	//                    carry the linkage; LC-07 requires a
	//                    live likeness consent for USER_TWIN.
	//   MODEL_API      — generated by a third-party model API
	//                    (e.g. SD / Veo). No persona linkage.
	//   UNKNOWN        — the producer did not declare. Mark-
	//                    MediaReady rejects with
	//                    AI_LABEL_MISSING; this is the
	//                    fail-closed gate.
	AIGenerationSource string `json:"aiGenerationSource,omitempty"`
	AIGenerated        bool   `json:"aiGenerated"`
	// PersonaID is set when AIGenerationSource == AI_PERSONA.
	// For PersonaType == USER_TWIN, SubjectID is the real
	// person whose likeness is used; the persona service
	// looks up the live consent for (PersonaID, SubjectID).
	PersonaID string `json:"personaId,omitempty"`
	SubjectID string `json:"subjectId,omitempty"`
	// LikenessConsentID is stamped at MarkMediaReady time so
	// a regulator can recover 'this asset was published
	// under consent X'. Empty for non-AI / CREATIVE assets.
	LikenessConsentID string `json:"likenessConsentId,omitempty"`
}

// MediaVariant is an immutable, recipe-versioned representation for one UI purpose.
// ORIGINAL remains immutable; a recipe upgrade creates another row instead of overwriting it.
type MediaVariant struct {
	MediaVariantID string    `json:"mediaVariantId"`
	MediaAssetID   string    `json:"mediaAssetId"`
	Purpose        string    `json:"purpose"`
	RecipeVersion  string    `json:"recipeVersion"`
	Format         string    `json:"format"`
	Width          int       `json:"width"`
	Height         int       `json:"height"`
	Bytes          int64     `json:"bytes,omitempty"`
	StorageKey     string    `json:"storageKey"`
	ContentHash    string    `json:"contentHash,omitempty"`
	Status         string    `json:"status"`
	CreatedAt      time.Time `json:"createdAt"`
	UpdatedAt      time.Time `json:"updatedAt"`
}

type ProcessingJob struct {
	JobID         string    `json:"jobId"`
	MediaAssetID  string    `json:"mediaAssetId"`
	RecipeVersion string    `json:"recipeVersion"`
	Status        string    `json:"status"`
	Attempts      int       `json:"attempts"`
	AvailableAt   time.Time `json:"availableAt"`
	LastError     string    `json:"lastError,omitempty"`
}

// VideoMetadata 是 ffprobe 输出（时长/分辨率/codec/rotation）。
type VideoMetadata struct {
	Width      int    `json:"width"`
	Height     int    `json:"height"`
	DurationMs int64  `json:"durationMs"`
	Codec      string `json:"codec"`
	HasAudio   bool   `json:"hasAudio"`
	// AudioCodec：音频流 codec 名（aac/opus/…）。纯音频资产（AUDIO）用它填 asset.Codec。
	AudioCodec string `json:"audioCodec,omitempty"`
}

// Processor 是媒体处理链接口（worker 实现，dev 用本地 ffmpeg）。
type Processor interface {
	// Process 处理原文件 → 标准 MP4 + thumbnail，返回播放/缩略图存储 key 和元数据。
	Process(ctx context.Context, originalPath string) (ProcessResult, error)
}

// ProcessResult 是处理结果。
type ProcessResult struct {
	PlaybackStorageKey  string
	ThumbnailStorageKey string
	Metadata            VideoMetadata
}

type Repository interface {
	CreateAsset(ctx context.Context, a MediaAsset) error
	GetAsset(ctx context.Context, id string) (MediaAsset, error)
	UpdateAsset(ctx context.Context, a MediaAsset, expectedStatus string) error
	Snapshot(ctx context.Context) ([]MediaAsset, error)
	UpsertVariant(ctx context.Context, variant MediaVariant) error
	GetVariant(ctx context.Context, variantID string) (MediaVariant, error)
	ListVariants(ctx context.Context, mediaAssetID string) ([]MediaVariant, error)
	EnqueueProcessingJob(ctx context.Context, job ProcessingJob) error
	// UpdateCompositionHint 仅更新 composition hint 字段（worker 跑完 ONNX/几何 推理后调用）。
	// 失败不阻塞：FAILED 状态独立保留。
	UpdateCompositionHint(ctx context.Context, assetID string, hint *MediaCompositionHint) error
}

type ProcessingJobRepository interface {
	ClaimProcessingJobs(ctx context.Context, workerID string, limit int, now time.Time) ([]ProcessingJob, error)
	MarkProcessingJobCompleted(ctx context.Context, workerID, jobID string, completedAt time.Time) error
	MarkProcessingJobFailed(ctx context.Context, workerID, jobID, reason string, nextAttemptAt time.Time, deadLetter bool) error
}

var (
	ErrAssetNotFound     = errors.New("media asset not found")
	ErrStatusTransition  = errors.New("invalid status transition")
	ErrMediaNotOwner     = errors.New("media asset owner mismatch")
	ErrUploadTooLarge    = errors.New("media upload too large")
	ErrMediaTypeMismatch = errors.New("media content type does not match declaration")
	ErrOriginalImmutable = errors.New("original media object is immutable")
	ErrUploadOffset      = errors.New("media upload offset mismatch")
	ErrUploadLength      = errors.New("media upload length mismatch")
	ErrChunkChecksum     = errors.New("media upload chunk checksum mismatch")
)

type UploadProgress struct {
	Offset   int64 `json:"offset"`
	Total    int64 `json:"total,omitempty"`
	Complete bool  `json:"complete"`
}

type MemoryRepository struct {
	mu       sync.Mutex
	assets   map[string]MediaAsset
	variants map[string]MediaVariant
	jobs     map[string]memoryProcessingJob
	events   []event.DomainEvent
}

type memoryProcessingJob struct {
	job    ProcessingJob
	worker string
}

func NewMemoryRepository() *MemoryRepository {
	return &MemoryRepository{assets: make(map[string]MediaAsset), variants: make(map[string]MediaVariant), jobs: make(map[string]memoryProcessingJob)}
}

func (r *MemoryRepository) CreateAsset(_ context.Context, a MediaAsset) error {
	r.mu.Lock()
	defer r.mu.Unlock()
	if _, exists := r.assets[a.MediaAssetID]; exists {
		return errors.New("asset already exists")
	}
	r.assets[a.MediaAssetID] = a
	return nil
}

func (r *MemoryRepository) GetAsset(_ context.Context, id string) (MediaAsset, error) {
	r.mu.Lock()
	defer r.mu.Unlock()
	a, exists := r.assets[id]
	if !exists {
		return MediaAsset{}, ErrAssetNotFound
	}
	return a, nil
}

func (r *MemoryRepository) UpdateAsset(_ context.Context, a MediaAsset, expectedStatus string) error {
	r.mu.Lock()
	defer r.mu.Unlock()
	current, exists := r.assets[a.MediaAssetID]
	if !exists {
		return ErrAssetNotFound
	}
	if current.ProcessingStatus != expectedStatus {
		return ErrStatusTransition
	}
	r.assets[a.MediaAssetID] = a
	return nil
}

func (r *MemoryRepository) UpdateCompositionHint(_ context.Context, assetID string, hint *MediaCompositionHint) error {
	r.mu.Lock()
	defer r.mu.Unlock()
	asset, ok := r.assets[assetID]
	if !ok {
		return ErrAssetNotFound
	}
	// hint=nil 表示清空 (worker 调取失败后显式置 UNKNOWN)
	asset.CompositionHint = hint
	asset.UpdatedAt = time.Now().UTC()
	r.assets[assetID] = asset
	return nil
}

func (r *MemoryRepository) Snapshot(_ context.Context) ([]MediaAsset, error) {
	r.mu.Lock()
	defer r.mu.Unlock()
	result := make([]MediaAsset, 0, len(r.assets))
	for _, a := range r.assets {
		result = append(result, a)
	}
	sort.Slice(result, func(i, j int) bool { return result[i].CreatedAt.After(result[j].CreatedAt) })
	return result, nil
}

func (r *MemoryRepository) UpsertVariant(_ context.Context, variant MediaVariant) error {
	r.mu.Lock()
	defer r.mu.Unlock()
	key := variant.MediaAssetID + ":" + variant.Purpose + ":" + variant.RecipeVersion
	r.variants[key] = variant
	return nil
}

func (r *MemoryRepository) ListVariants(_ context.Context, mediaAssetID string) ([]MediaVariant, error) {
	r.mu.Lock()
	defer r.mu.Unlock()
	result := []MediaVariant{}
	for _, variant := range r.variants {
		if variant.MediaAssetID == mediaAssetID {
			result = append(result, variant)
		}
	}
	sort.Slice(result, func(i, j int) bool { return result[i].Purpose < result[j].Purpose })
	return result, nil
}

func (r *MemoryRepository) GetVariant(_ context.Context, variantID string) (MediaVariant, error) {
	r.mu.Lock()
	defer r.mu.Unlock()
	for _, variant := range r.variants {
		if variant.MediaVariantID == variantID {
			return variant, nil
		}
	}
	return MediaVariant{}, ErrAssetNotFound
}

type Service struct {
	mu                   sync.Mutex
	repository           Repository
	reviewDecisionRepo   ReviewDecisionRepository
	processor            Processor
	clock                clock.Clock
	storeDir             string
	logger               *log.Logger
	// personaService is the LC-07 likeness-consent
	// reader. Wired from cmd/api/main.go. nil means the
	// legacy test server is in use; markReady falls back to
	// a permissive path so existing tests pass. Production
	// deployments must wire it.
	personaService *aipersona.Service
}

func New() *Service {
	return NewWithReviewDecisionRepository(NewMemoryRepository(), NewMemoryReviewDecisionRepository(), nil)
}

// NewWithDependencies 注入 repository 和 processor。
// processor 为 nil 时用 NoopProcessor（单测/无 ffmpeg 环境）。
// reviewDecisionRepo 为 nil 时用 MemoryReviewDecisionRepository,
// 是默认 (R15.18 让 memory 模式也能 持久化决策)。
func NewWithDependencies(repository Repository, processor Processor) *Service {
	return NewWithReviewDecisionRepository(repository, NewMemoryReviewDecisionRepository(), processor)
}

// NewWithReviewDecisionRepository R15.18 入口: 注入决策仓库。
func NewWithReviewDecisionRepository(repository Repository, reviewDecisionRepo ReviewDecisionRepository, processor Processor) *Service {
	if repository == nil {
		repository = NewMemoryRepository()
	}
	if reviewDecisionRepo == nil {
		reviewDecisionRepo = NewMemoryReviewDecisionRepository()
	}
	return &Service{repository: repository, reviewDecisionRepo: reviewDecisionRepo, processor: processor, clock: clock.System{}, storeDir: filepath.Join(".", "media_store")}
}

// SetStoreDir 覆盖媒体文件本地目录（与 FFmpegProcessor.StoreDir 对齐）。
func (s *Service) SetStoreDir(dir string) {
	s.storeDir = dir
}

// SetLogger 注入 logger（默认 = log.Default()）。v2 派生失败会调这个。
func (s *Service) SetLogger(l *log.Logger) {
	if l != nil {
		s.logger = l
	}
}

// WithAIPersonaService wires the LC-07 likeness-consent
// reader. Returns the receiver so the call composes with
// other initialisers.
func (s *Service) WithAIPersonaService(p *aipersona.Service) *Service {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.personaService = p
	return s
}

// SaveUpload persists the authenticated owner's raw upload under the storage
// key registered by CreateMediaAsset. The command state remains UPLOADING;
// CompleteMediaUpload and ProcessMediaAsset still own lifecycle transitions.
func (s *Service) SaveUpload(ctx context.Context, id string, ownerPrincipalID string, source io.Reader, maxBytes int64) (MediaAsset, error) {
	s.mu.Lock()
	defer s.mu.Unlock()
	return s.saveUploadLocked(ctx, id, ownerPrincipalID, source, maxBytes)
}

func (s *Service) saveUploadLocked(ctx context.Context, id string, ownerPrincipalID string, source io.Reader, maxBytes int64) (MediaAsset, error) {
	asset, err := s.repository.GetAsset(ctx, id)
	if err != nil {
		return MediaAsset{}, err
	}
	if asset.OwnerPrincipalID != ownerPrincipalID {
		return MediaAsset{}, ErrMediaNotOwner
	}
	if asset.ProcessingStatus != "UPLOADING" {
		return MediaAsset{}, ErrStatusTransition
	}
	key := asset.OriginalStorageKey
	if key == "" || filepath.Base(key) != key || strings.Contains(key, "..") {
		return MediaAsset{}, errors.New("invalid storage key")
	}
	if maxBytes <= 0 {
		maxBytes = 20 << 20
	}
	if err := os.MkdirAll(s.storeDir, 0o750); err != nil {
		return MediaAsset{}, err
	}
	destinationPath := filepath.Join(s.storeDir, key)
	temporary, err := os.CreateTemp(s.storeDir, ".proxy-upload-*")
	if err != nil {
		return MediaAsset{}, err
	}
	temporaryPath := temporary.Name()
	committed := false
	defer func() {
		_ = temporary.Close()
		if !committed {
			_ = os.Remove(temporaryPath)
		}
	}()
	buffered := bufio.NewReader(source)
	header, peekErr := buffered.Peek(512)
	if peekErr != nil && !errors.Is(peekErr, io.EOF) {
		return MediaAsset{}, peekErr
	}
	detectedMime := detectMediaMime(header)
	if !mediaMimeAllowed(asset.MediaType, asset.MimeType, detectedMime) {
		return MediaAsset{}, ErrMediaTypeMismatch
	}
	hasher := sha256.New()
	written, err := io.Copy(io.MultiWriter(temporary, hasher), io.LimitReader(buffered, maxBytes+1))
	if err != nil {
		return MediaAsset{}, err
	}
	if written > maxBytes {
		return MediaAsset{}, ErrUploadTooLarge
	}
	if err := temporary.Sync(); err != nil {
		return MediaAsset{}, err
	}
	if err := temporary.Close(); err != nil {
		return MediaAsset{}, err
	}
	if asset.MediaType == "IMAGE" {
		metadata := readSourceImageMetadata(ctx, temporaryPath, detectedMime)
		if metadata.Width > 0 && metadata.Height > 0 {
			asset.Width = metadata.Width
			asset.Height = metadata.Height
		}
		asset.Orientation = metadata.Orientation
		asset.ColorSpace = metadata.ColorSpace
		asset.HasAlpha = metadata.HasAlpha
		asset.Animated = metadata.Animated
	}
	// Link is exclusive: unlike Rename on Unix it cannot silently overwrite an
	// existing ORIGINAL object. The temp file lives in the same directory/filesystem.
	if err := os.Link(temporaryPath, destinationPath); err != nil {
		if errors.Is(err, os.ErrExist) {
			incomingHash := hex.EncodeToString(hasher.Sum(nil))
			// A PUT whose response was lost may be retried. The exact same bytes
			// are idempotent; different bytes can never replace ORIGINAL.
			if asset.SourceBytes == written && asset.ChecksumSHA256 != "" && asset.ChecksumSHA256 == incomingHash {
				_ = os.Remove(temporaryPath)
				committed = true
				if variantErr := s.persistOriginalVariant(ctx, asset); variantErr != nil {
					return MediaAsset{}, variantErr
				}
				return asset, nil
			}
			return MediaAsset{}, ErrOriginalImmutable
		}
		return MediaAsset{}, err
	}
	originalPersisted := true
	defer func() {
		if originalPersisted {
			_ = os.Remove(destinationPath)
		}
	}()
	asset.SourceBytes = written
	asset.ChecksumSHA256 = hex.EncodeToString(hasher.Sum(nil))
	asset.MimeType = detectedMime
	if err := s.repository.UpdateAsset(ctx, asset, "UPLOADING"); err != nil {
		return MediaAsset{}, err
	}
	originalPersisted = false
	if err := s.persistOriginalVariant(ctx, asset); err != nil {
		return MediaAsset{}, err
	}
	_ = os.Remove(temporaryPath)
	committed = true
	return asset, nil
}

// UploadOffset returns the durable byte boundary for a resumable upload. The
// partial object lives beside the immutable ORIGINAL so an API restart does not
// force the client to resend accepted chunks.
func (s *Service) UploadOffset(ctx context.Context, id, ownerPrincipalID string) (UploadProgress, error) {
	s.mu.Lock()
	defer s.mu.Unlock()
	asset, err := s.uploadingAsset(ctx, id, ownerPrincipalID)
	if err != nil {
		return UploadProgress{}, err
	}
	if asset.SourceBytes > 0 {
		return UploadProgress{Offset: asset.SourceBytes, Total: asset.SourceBytes, Complete: true}, nil
	}
	info, err := os.Stat(s.partialUploadPath(asset))
	if errors.Is(err, os.ErrNotExist) {
		return UploadProgress{}, nil
	}
	if err != nil {
		return UploadProgress{}, err
	}
	return UploadProgress{Offset: info.Size()}, nil
}

// SaveUploadChunk appends exactly one Content-Range chunk. A replay of an
// already committed chunk is accepted only when its bytes are identical.
func (s *Service) SaveUploadChunk(ctx context.Context, id, ownerPrincipalID string, source io.Reader, start, end, total, maxBytes int64, expectedSHA256 string) (UploadProgress, error) {
	s.mu.Lock()
	defer s.mu.Unlock()
	asset, err := s.uploadingAsset(ctx, id, ownerPrincipalID)
	if err != nil {
		return UploadProgress{}, err
	}
	if start < 0 || end < start || total <= end || total > maxBytes {
		return UploadProgress{}, ErrUploadLength
	}
	expectedBytes := end - start + 1
	chunk, err := io.ReadAll(io.LimitReader(source, expectedBytes+1))
	if err != nil {
		return UploadProgress{}, err
	}
	if int64(len(chunk)) != expectedBytes {
		return UploadProgress{}, ErrUploadLength
	}
	hash := sha256.Sum256(chunk)
	if expectedSHA256 == "" || !strings.EqualFold(expectedSHA256, hex.EncodeToString(hash[:])) {
		return UploadProgress{}, ErrChunkChecksum
	}
	if err := os.MkdirAll(s.storeDir, 0o750); err != nil {
		return UploadProgress{}, err
	}
	partialPath := s.partialUploadPath(asset)
	file, err := os.OpenFile(partialPath, os.O_CREATE|os.O_RDWR, 0o600)
	if err != nil {
		return UploadProgress{}, err
	}
	defer file.Close()
	info, err := file.Stat()
	if err != nil {
		return UploadProgress{}, err
	}
	current := info.Size()
	if start < current {
		if end+1 > current {
			return UploadProgress{Offset: current, Total: total}, ErrUploadOffset
		}
		existing := make([]byte, len(chunk))
		if _, err := file.ReadAt(existing, start); err != nil || !bytes.Equal(existing, chunk) {
			return UploadProgress{Offset: current, Total: total}, ErrChunkChecksum
		}
		return UploadProgress{Offset: current, Total: total, Complete: current == total}, nil
	}
	if start != current {
		return UploadProgress{Offset: current, Total: total}, ErrUploadOffset
	}
	if _, err := file.WriteAt(chunk, start); err != nil {
		return UploadProgress{}, err
	}
	if err := file.Sync(); err != nil {
		return UploadProgress{}, err
	}
	current = end + 1
	if current < total {
		return UploadProgress{Offset: current, Total: total}, nil
	}
	if err := file.Close(); err != nil {
		return UploadProgress{}, err
	}
	assembled, err := os.Open(partialPath)
	if err != nil {
		return UploadProgress{}, err
	}
	_, saveErr := s.saveUploadLocked(ctx, id, ownerPrincipalID, assembled, maxBytes)
	closeErr := assembled.Close()
	if saveErr != nil {
		return UploadProgress{}, saveErr
	}
	if closeErr != nil {
		return UploadProgress{}, closeErr
	}
	if err := os.Remove(partialPath); err != nil && !errors.Is(err, os.ErrNotExist) {
		return UploadProgress{}, err
	}
	return UploadProgress{Offset: total, Total: total, Complete: true}, nil
}

func (s *Service) uploadingAsset(ctx context.Context, id, ownerPrincipalID string) (MediaAsset, error) {
	asset, err := s.repository.GetAsset(ctx, id)
	if err != nil {
		return MediaAsset{}, err
	}
	if asset.OwnerPrincipalID != ownerPrincipalID {
		return MediaAsset{}, ErrMediaNotOwner
	}
	if asset.ProcessingStatus != "UPLOADING" {
		return MediaAsset{}, ErrStatusTransition
	}
	if asset.OriginalStorageKey == "" || filepath.Base(asset.OriginalStorageKey) != asset.OriginalStorageKey || strings.Contains(asset.OriginalStorageKey, "..") {
		return MediaAsset{}, errors.New("invalid storage key")
	}
	return asset, nil
}

func (s *Service) partialUploadPath(asset MediaAsset) string {
	return filepath.Join(s.storeDir, "."+asset.MediaAssetID+"."+asset.OriginalStorageKey+".part")
}

func (s *Service) persistOriginalVariant(ctx context.Context, asset MediaAsset) error {
	now := s.clock.Now().UTC()
	return s.repository.UpsertVariant(ctx, MediaVariant{
		MediaVariantID: "mv_" + asset.MediaAssetID + "_original_v1",
		MediaAssetID:   asset.MediaAssetID,
		Purpose:        "ORIGINAL",
		RecipeVersion:  "original_v1",
		Format:         asset.MimeType,
		Width:          asset.Width,
		Height:         asset.Height,
		Bytes:          asset.SourceBytes,
		StorageKey:     asset.OriginalStorageKey,
		ContentHash:    asset.ChecksumSHA256,
		Status:         "READY",
		CreatedAt:      now,
		UpdatedAt:      now,
	})
}

func detectMediaMime(header []byte) string {
	if len(header) >= 12 && string(header[4:8]) == "ftyp" {
		brand := string(header[8:12])
		switch brand {
		case "heic", "heix", "hevc", "hevx", "mif1", "msf1":
			return "image/heic"
		case "avif", "avis":
			return "image/avif"
		}
	}
	return http.DetectContentType(header)
}

func mediaMimeAllowed(mediaType, declared, detected string) bool {
	expectedPrefix := "image/"
	switch mediaType {
	case "VIDEO":
		expectedPrefix = "video/"
	case "AUDIO":
		// 录音产物是 m4a/mp4 容器，http.DetectContentType 探测为 video/mp4；
		// 只要求声明类型以 audio/ 开头且探测结果不是图片即可，精确校验交给 ffprobe。
		normalizedDeclared := strings.ToLower(strings.TrimSpace(strings.Split(declared, ";")[0]))
		return strings.HasPrefix(normalizedDeclared, "audio/") && !strings.HasPrefix(detected, "image/")
	}
	if !strings.HasPrefix(detected, expectedPrefix) {
		return false
	}
	normalize := func(value string) string {
		value = strings.ToLower(strings.TrimSpace(strings.Split(value, ";")[0]))
		if value == "image/jpg" {
			return "image/jpeg"
		}
		if value == "image/heif" {
			return "image/heic"
		}
		return value
	}
	return declared == "" || normalize(declared) == normalize(detected)
}

// ResolveServingPath 把 READY 资产的 storage key 解析为本地文件路径，供
// GET /v1/media/play|thumb/{id} 直接 ServeFile（客户端播 MP4/图片 URL）。
// kind: "play" | "thumb"（thumb 缺失时降级回 playback 文件）。
// fail-closed：非 READY / key 含路径分隔符（防目录穿越）一律拒绝。
func (s *Service) ResolveServingPath(ctx context.Context, id string, kind string) (string, error) {
	asset, err := s.repository.GetAsset(ctx, id)
	if err != nil {
		return "", err
	}
	if asset.ProcessingStatus != "READY" {
		return "", errors.New("media not ready")
	}
	if asset.ModerationStatus != "APPROVED" || asset.VisibilityClass != "PUBLIC" {
		return "", errors.New("media is not publicly deliverable")
	}
	key := asset.PlaybackStorageKey
	if kind == "thumb" {
		if asset.ThumbnailStorageKey != "" {
			key = asset.ThumbnailStorageKey
		}
	}
	if key == "" || strings.ContainsAny(key, "/\\") || strings.Contains(key, "..") {
		return "", errors.New("invalid storage key")
	}
	return filepath.Join(s.storeDir, key), nil
}

func (s *Service) ResolveVariantPath(ctx context.Context, variantID string) (string, error) {
	variant, err := s.repository.GetVariant(ctx, variantID)
	if err != nil {
		return "", err
	}
	if variant.Status != "READY" {
		return "", errors.New("variant not ready")
	}
	if variant.Purpose == "ORIGINAL" {
		return "", errors.New("original variant is not a public delivery resource")
	}
	asset, err := s.repository.GetAsset(ctx, variant.MediaAssetID)
	if err != nil {
		return "", err
	}
	if asset.ProcessingStatus != "READY" || asset.ModerationStatus != "APPROVED" || asset.VisibilityClass != "PUBLIC" {
		return "", errors.New("variant is not publicly deliverable")
	}
	if variant.StorageKey == "" || strings.ContainsAny(variant.StorageKey, "/\\") || strings.Contains(variant.StorageKey, "..") {
		return "", errors.New("invalid variant storage key")
	}
	return filepath.Join(s.storeDir, variant.StorageKey), nil
}

func (s *Service) ListReadyVariants(ctx context.Context, mediaAssetID string) ([]MediaVariant, error) {
	variants, err := s.repository.ListVariants(ctx, mediaAssetID)
	if err != nil {
		return nil, err
	}
	ready := make([]MediaVariant, 0, len(variants))
	for _, variant := range variants {
		if variant.Status == "READY" {
			ready = append(ready, variant)
		}
	}
	return ready, nil
}

// AuthorizeForStorefront promotes technically approved media uploads to
// PUBLIC so store album and menu photos are remotely viewable (thumb/play
// URLs). Storefronts are public surfaces; same trust shape as posts.
func (s *Service) AuthorizeForStorefront(ctx context.Context, ids []string, ownerPrincipalID string) error {
	return s.AuthorizeForPost(ctx, ids, ownerPrincipalID, "PUBLIC")
}

// AuthorizeForPost is the server-owned publication transition. READY alone is
// never public: only the owner can attach technically approved media, and the
// asset receives exactly the Post visibility class inside the command transaction.
func (s *Service) AuthorizeForPost(ctx context.Context, ids []string, ownerPrincipalID, visibility string) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	if visibility != "PUBLIC" && visibility != "FOLLOWERS" && visibility != "AGENT_ONLY" {
		return errors.New("unsupported media visibility")
	}
	for _, id := range ids {
		asset, err := s.repository.GetAsset(ctx, id)
		if err != nil {
			return err
		}
		if asset.OwnerPrincipalID != ownerPrincipalID {
			return ErrMediaNotOwner
		}
		if asset.ProcessingStatus != "READY" || asset.ModerationStatus != "APPROVED" {
			return ErrStatusTransition
		}
		if asset.VisibilityClass != "OWNER_ONLY" && asset.VisibilityClass != visibility {
			return errors.New("media already bound to another visibility class")
		}
		if asset.VisibilityClass == visibility {
			continue
		}
		asset.VisibilityClass = visibility
		asset.UpdatedAt = s.clock.Now().UTC()
		if err := s.repository.UpdateAsset(ctx, asset, "READY"); err != nil {
			return err
		}
	}
	return nil
}

func (s *Service) Supports(commandType string) bool {
	switch commandType {
	case "CreateMediaAsset", "CompleteMediaUpload", "ProcessMediaAsset",
		"MarkMediaReady", "GetMediaAsset", "ListMediaAssets",
		// R15.17: admin review command — media 域接手 dispatch。
		"ReviewMediaAsset":
		return true
	default:
		return false
	}
}

func (s *Service) Handle(e command.Envelope) command.Result {
	return s.HandleContext(context.Background(), e)
}

func (s *Service) HandleContext(ctx context.Context, e command.Envelope) command.Result {
	s.mu.Lock()
	defer s.mu.Unlock()
	switch e.CommandType {
	case "CreateMediaAsset":
		return s.createAsset(ctx, e)
	case "CompleteMediaUpload":
		return s.completeUpload(ctx, e)
	case "ProcessMediaAsset":
		return s.processAsset(ctx, e)
	case "MarkMediaReady":
		return s.markReady(ctx, e)
	case "GetMediaAsset":
		return s.getAsset(ctx, e)
	case "ListMediaAssets":
		return s.listAssets(ctx, e)
	// R15.17: admin 手动 content review 路径。仅 operator (PROXY_OPERATOR_PRINCIPALS)
	// 可调用。ReviewMediaAsset 只能把 asset 从 QUARANTINED/APPROVED
	// 过渡到 REJECTED_CONTENT_NUDITY / _POLITICS / _VIOLENCE, 或
	// 从任一状态返回 APPROVED (unblock)。
	case "ReviewMediaAsset":
		return s.reviewMediaAsset(ctx, e)
	// R15.18: audit 列表 — operator 查 content review 决策历史。
	// 逻辑: operator in PROXY_OPERATOR_PRINCIPALS (server 门已验)
	// 看到所有 asset 的决策行,不能只看到自己作为 operator 的。
	// 按 mediaAssetId 过滤 (空 = 所有),按 reviewedAt 倒序。
	case "ListMediaReviewDecisions":
		return s.listMediaReviewDecisions(ctx, e)
	// R15.19: 修订决策 (append-only 加修订行)。amends 语义, 不改 prev
	// 行的 from/to/reason/operator — 只多 1 行 note="amends:<prev_id>:<reason>:<note>"
	// 钉审计历史。
	case "AmendMediaReviewDecision":
		return s.amendMediaReviewDecision(ctx, e)
	default:
		return command.Rejected(e, "MEDIA_COMMAND_UNSUPPORTED", "VALIDATION", "AFTER_USER_ACTION", "media.unsupported_command", nil)
	}
}

// ---------- CreateMediaAsset ----------
// 登记上传：拿到 upload URL（dev 返回本地直传路径），资产 = UPLOADING。

type createAssetPayload struct {
	MediaType          string `json:"mediaType"`
	OriginalStorageKey string `json:"originalStorageKey"`
	MimeType           string `json:"mimeType"`
	Width              int    `json:"width"`
	Height             int    `json:"height"`
	// R16.7-P1-K (LC-06) + R16.7-P1-I (LC-07): AI generation
	// provenance. Optional at CreateMediaAsset; the asset
	// is registered with source=USER_UPLOADED by default. AI
	// uploads (PersonaID set) are accepted as well; the
	// MarkMediaReady handler is the gate that enforces the
	// fail-closed behaviour.
	AIGenerationSource string `json:"aiGenerationSource,omitempty"`
	PersonaID          string `json:"personaId,omitempty"`
	SubjectID          string `json:"subjectId,omitempty"`
}

func (s *Service) createAsset(ctx context.Context, e command.Envelope) command.Result {
	var p createAssetPayload
	if !decode(e.Payload, &p) || p.MediaType == "" || p.OriginalStorageKey == "" {
		return command.Rejected(e, "INVALID_MEDIA_ASSET", "VALIDATION", "AFTER_USER_ACTION", "media.invalid_asset", nil)
	}
	if p.MediaType != "IMAGE" && p.MediaType != "VIDEO" && p.MediaType != "AUDIO" {
		return command.Rejected(e, "INVALID_MEDIA_TYPE", "VALIDATION", "AFTER_USER_ACTION", "media.invalid_type", map[string]any{"mediaType": p.MediaType})
	}
	// R16.7-P1-K (LC-06): normalize the AI source at the
	// boundary. Empty input defaults to USER_UPLOADED — that
	// is the only safe assumption (a user uploading a phone
	// photo cannot accidentally be tagged as AI). Unknown
	// non-empty values are rejected so the producer must
	// commit to a known source.
	aiSource := normalizeAIGenerationSource(p.AIGenerationSource)
	if p.AIGenerationSource != "" && aiSource == "UNKNOWN" {
		return command.Rejected(e, "INVALID_AI_GENERATION_SOURCE", "VALIDATION", "AFTER_USER_ACTION", "media.invalid_ai_source", map[string]any{"aiGenerationSource": p.AIGenerationSource})
	}
	// R16.7-P1-I (LC-07): when the asset is AI_PERSONA, the
	// persona id is required so the likeness-consent lookup
	// at MarkMediaReady has a target. SubjectID is also
	// required for USER_TWIN personas; the catalogue has it
	// on the persona row, but we accept it inline for the
	// simple case (one persona, one subject).
	if aiSource == "AI_PERSONA" && p.PersonaID == "" {
		return command.Rejected(e, "AI_PERSONA_ID_REQUIRED", "VALIDATION", "AFTER_USER_ACTION", "media.ai_persona_id_required", nil)
	}
	if aiSource == "AI_PERSONA" && p.PersonaID != "" && p.SubjectID == "" {
		// SubjectID is optional at create time; the media
		// service falls back to the asset's owner principal
		// at MarkMediaReady. This is the common case: the
		// user is uploading their own likeness.
		p.SubjectID = e.Principal.ID
	}
	now := s.clock.Now().UTC()
	asset := MediaAsset{
		MediaAssetID:       newID("ma_"),
		OwnerPrincipalType: e.Principal.Type,
		OwnerPrincipalID:   e.Principal.ID,
		MediaType:          p.MediaType,
		OriginalStorageKey: p.OriginalStorageKey,
		MimeType:           p.MimeType,
		Width:              p.Width,
		Height:             p.Height,
		ModerationStatus:   "QUARANTINED",
		VisibilityClass:    "OWNER_ONLY",
		ProcessingStatus:   "UPLOADING",
		CreatedAt:          now,
		UpdatedAt:          now,
		AIGenerationSource: aiSource,
		AIGenerated:        aiSource != "" && aiSource != "USER_UPLOADED",
		PersonaID:          p.PersonaID,
		SubjectID:          p.SubjectID,
	}
	domainEvents := []event.DomainEvent{event.New("MediaAssetCreated", "MediaAsset", asset.MediaAssetID, 1, e.Principal.ID, e.CorrelationID, e.CommandID, now, map[string]any{
		"mediaType": p.MediaType,
		"status":    "UPLOADING",
	})}
	if err := s.repository.CreateAsset(ctx, asset); err != nil {
		return command.Rejected(e, "MEDIA_CREATE_FAILED", "INTERNAL", "SAFE_RETRY", "media.create_failed", nil)
	}
	return acceptedWithPayload(e, "MediaAsset", asset.MediaAssetID, 1, "UPLOADING", map[string]any{
		"mediaAssetId": asset.MediaAssetID,
		"uploadUrl":    "/v1/media/upload/" + asset.MediaAssetID, // dev：本地直传端点
		"status":       "UPLOADING",
	}, domainEvents)
}

// ---------- CompleteMediaUpload ----------
// 上传完成 → PROCESSING（准备处理）。

type completeUploadPayload struct {
	OriginalStorageKey string `json:"originalStorageKey"`
}

func (s *Service) completeUpload(ctx context.Context, e command.Envelope) command.Result {
	var p completeUploadPayload
	if !decode(e.Payload, &p) || p.OriginalStorageKey == "" {
		return command.Rejected(e, "INVALID_COMPLETE_UPLOAD", "VALIDATION", "AFTER_USER_ACTION", "media.invalid_complete_upload", nil)
	}
	asset, err := s.repository.GetAsset(ctx, e.Target.ID)
	if errors.Is(err, ErrAssetNotFound) {
		return command.Rejected(e, "MEDIA_ASSET_NOT_FOUND", "BUSINESS_STATE", "AFTER_USER_ACTION", "media.asset_not_found", nil)
	}
	if err != nil {
		return command.Rejected(e, "MEDIA_READ_FAILED", "INTERNAL", "SAFE_RETRY", "media.read_failed", nil)
	}
	if asset.OwnerPrincipalID != e.Principal.ID {
		return command.Rejected(e, "MEDIA_NOT_OWNER", "AUTHORIZATION", "AFTER_USER_ACTION", "media.not_owner", nil)
	}
	if asset.ProcessingStatus != "UPLOADING" {
		return command.Rejected(e, "MEDIA_NOT_UPLOADING", "BUSINESS_STATE", "AFTER_USER_ACTION", "media.not_uploading", map[string]any{"status": asset.ProcessingStatus})
	}
	if asset.OriginalStorageKey != p.OriginalStorageKey {
		return command.Rejected(e, "STORAGE_KEY_MISMATCH", "VALIDATION", "AFTER_USER_ACTION", "media.storage_key_mismatch", nil)
	}
	asset.ProcessingStatus = "PROCESSING"
	asset.UpdatedAt = s.clock.Now().UTC()
	domainEvents := []event.DomainEvent{event.New("MediaUploadCompleted", "MediaAsset", asset.MediaAssetID, 1, e.Principal.ID, e.CorrelationID, e.CommandID, asset.UpdatedAt, map[string]any{
		"status": "PROCESSING",
	})}
	if err := s.repository.UpdateAsset(ctx, asset, "UPLOADING"); err != nil {
		return command.Rejected(e, "MEDIA_UPDATE_FAILED", "INTERNAL", "SAFE_RETRY", "media.update_failed", nil)
	}
	if err := s.repository.EnqueueProcessingJob(ctx, processingJobFor(asset, asset.UpdatedAt)); err != nil {
		return command.Rejected(e, "MEDIA_JOB_ENQUEUE_FAILED", "INTERNAL", "SAFE_RETRY", "media.job_enqueue_failed", nil)
	}
	return command.Accepted(e, "MediaAsset", asset.MediaAssetID, 1, "PROCESSING", eventRefs(domainEvents))
}

// ---------- ProcessMediaAsset ----------
// Compatibility command: processing is always performed by the durable worker.
// Calling this command only confirms/repairs the idempotent queue entry; it
// never runs ffmpeg in the API request thread.

type processPayload struct {
	OriginalPath string `json:"originalPath"` // dev：本地原文件路径（模拟 Object Storage 取回）
}

func (s *Service) processAsset(ctx context.Context, e command.Envelope) command.Result {
	var p processPayload
	if !decode(e.Payload, &p) {
		return command.Rejected(e, "INVALID_PROCESS_REQUEST", "VALIDATION", "AFTER_USER_ACTION", "media.invalid_process", nil)
	}
	// ffmpeg 支持 http:// / concat: / subfile: 等协议输入：客户端可控路径不做
	// 收敛会变成任意文件读取 + SSRF。只接受本地普通文件路径。
	if p.OriginalPath != "" && !isSafeLocalPath(p.OriginalPath) {
		return command.Rejected(e, "UNSAFE_MEDIA_PATH", "VALIDATION", "AFTER_USER_ACTION", "media.unsafe_path", nil)
	}
	asset, err := s.repository.GetAsset(ctx, e.Target.ID)
	if errors.Is(err, ErrAssetNotFound) {
		return command.Rejected(e, "MEDIA_ASSET_NOT_FOUND", "BUSINESS_STATE", "AFTER_USER_ACTION", "media.asset_not_found", nil)
	}
	if err != nil {
		return command.Rejected(e, "MEDIA_READ_FAILED", "INTERNAL", "SAFE_RETRY", "media.read_failed", nil)
	}
	if asset.OwnerPrincipalID != e.Principal.ID {
		return command.Rejected(e, "MEDIA_NOT_OWNER", "AUTHORIZATION", "AFTER_USER_ACTION", "media.not_owner", nil)
	}
	if asset.ProcessingStatus != "PROCESSING" {
		return command.Rejected(e, "MEDIA_NOT_PROCESSING", "BUSINESS_STATE", "AFTER_USER_ACTION", "media.not_processing", map[string]any{"status": asset.ProcessingStatus})
	}
	if err := s.repository.EnqueueProcessingJob(ctx, processingJobFor(asset, s.clock.Now().UTC())); err != nil {
		return command.Rejected(e, "MEDIA_JOB_ENQUEUE_FAILED", "INTERNAL", "SAFE_RETRY", "media.job_enqueue_failed", nil)
	}
	return acceptedWithPayload(e, "MediaAsset", asset.MediaAssetID, 1, "PROCESSING", map[string]any{
		"mediaAssetId": asset.MediaAssetID, "processingStatus": "PROCESSING",
	}, nil)
}

// ---------- MarkMediaReady ----------
// 手动标 READY（外部 worker 已处理完的场景）。API 边界已将其限定为 operator
// 命令；这里仍坚持 PROCESSING 前置，禁止从 UPLOADING 直接跳过处理链。

type markReadyPayload struct {
	PlaybackStorageKey  string `json:"playbackStorageKey"`
	ThumbnailStorageKey string `json:"thumbnailStorageKey"`
	DurationMs          int64  `json:"durationMs"`
	Width               int    `json:"width"`
	Height              int    `json:"height"`
	Codec               string `json:"codec"`
}

func (s *Service) markReady(ctx context.Context, e command.Envelope) command.Result {
	var p markReadyPayload
	if !decode(e.Payload, &p) {
		return command.Rejected(e, "INVALID_MARK_READY", "VALIDATION", "AFTER_USER_ACTION", "media.invalid_mark_ready", nil)
	}
	asset, err := s.repository.GetAsset(ctx, e.Target.ID)
	if errors.Is(err, ErrAssetNotFound) {
		return command.Rejected(e, "MEDIA_ASSET_NOT_FOUND", "BUSINESS_STATE", "AFTER_USER_ACTION", "media.asset_not_found", nil)
	}
	if err != nil {
		return command.Rejected(e, "MEDIA_READ_FAILED", "INTERNAL", "SAFE_RETRY", "media.read_failed", nil)
	}
	expectedStatus := asset.ProcessingStatus
	if expectedStatus != "PROCESSING" {
		return command.Rejected(e, "MEDIA_NOT_PROCESSABLE", "BUSINESS_STATE", "AFTER_USER_ACTION", "media.not_processable", map[string]any{"status": asset.ProcessingStatus})
	}
	// R16.7-P1-K (LC-06) fail-closed gate: an asset whose
	// AIGenerationSource is UNKNOWN cannot be promoted to
	// READY. The producer must re-declare the source. This is
	// the practical shape of 'fail closed when the AI label
	// cannot be produced' (Vietnam 134/2025/QH15 Art. 12):
	// the platform never publishes unlabeled media, even
	// when the asset looks ready. We do not auto-reject on
	// USER_UPLOADED — the absence of an AI label is
	// meaningful there, not a missing label.
	if asset.AIGenerationSource == "UNKNOWN" {
		return command.Rejected(e, "AI_LABEL_MISSING", "VALIDATION", "AFTER_USER_ACTION", "media.ai_label_missing", map[string]any{"mediaAssetId": asset.MediaAssetID})
	}
	// R16.7-P1-I (LC-07) fail-closed gate: an AI_PERSONA
	// asset must have a live likeness consent for the
	// (persona, subject) tuple. We resolve SubjectID against
	// the asset's subject field first, then fall back to the
	// owner. The check is only enforced when the persona
	// service is wired; the legacy test path skips the
	// consent check so the existing test suite keeps
	// passing. Production deployments must wire it.
	if asset.AIGenerationSource == "AI_PERSONA" && asset.PersonaID != "" && s.personaService != nil {
		subject := asset.SubjectID
		if subject == "" {
			subject = asset.OwnerPrincipalID
		}
		persona, perr := s.personaService.GetPersona(ctx, asset.PersonaID)
		if perr != nil {
			return command.Rejected(e, "AI_PERSONA_NOT_FOUND", "BUSINESS_STATE", "AFTER_USER_ACTION", "media.ai_persona_not_found", map[string]any{"personaId": asset.PersonaID})
		}
		// CREATIVE personas have no real-person likeness;
		// the consent gate is for USER_TWIN only.
		if persona.PersonaType == aipersona.PersonaTypeUserTwin {
			consent, cerr := s.personaService.HasLiveConsent(ctx, asset.PersonaID, subject)
			if cerr != nil {
				return command.Rejected(e, "AI_LIKENESS_CONSENT_LOOKUP_FAILED", "INTERNAL", "SAFE_RETRY", "media.likeness_consent_lookup_failed", map[string]any{"personaId": asset.PersonaID, "subjectId": subject, "error": cerr.Error()})
			}
			if consent == nil {
				return command.Rejected(e, "AI_LIKENESS_CONSENT_MISSING", "VALIDATION", "AFTER_USER_ACTION", "media.likeness_consent_missing", map[string]any{"personaId": asset.PersonaID, "subjectId": subject, "personaType": string(persona.PersonaType)})
			}
			asset.LikenessConsentID = consent.ID
		}
	}
	asset.ProcessingStatus = "READY"
	if p.PlaybackStorageKey != "" {
		asset.PlaybackStorageKey = p.PlaybackStorageKey
	}
	if p.ThumbnailStorageKey != "" {
		asset.ThumbnailStorageKey = p.ThumbnailStorageKey
	}
	asset.DurationMs = p.DurationMs
	asset.Width = p.Width
	asset.Height = p.Height
	asset.Codec = p.Codec
	asset.PlaybackURL = "/v1/media/play/" + asset.MediaAssetID
	asset.ThumbnailURL = "/v1/media/thumb/" + asset.MediaAssetID
	asset.UpdatedAt = s.clock.Now().UTC()
	domainEvents := []event.DomainEvent{event.New("MediaAssetReady", "MediaAsset", asset.MediaAssetID, 1, e.Principal.ID, e.CorrelationID, e.CommandID, asset.UpdatedAt, map[string]any{
		"status": "READY", "mediaType": asset.MediaType,
	})}
	if err := s.repository.UpdateAsset(ctx, asset, expectedStatus); err != nil {
		return command.Rejected(e, "MEDIA_UPDATE_FAILED", "INTERNAL", "SAFE_RETRY", "media.update_failed", nil)
	}
	return command.Accepted(e, "MediaAsset", asset.MediaAssetID, 1, "READY", eventRefs(domainEvents))
}

// ---------- ReviewMediaAsset (R15.17) ----------
// admin 手动 content review 路径。由 operator (PROXY_OPERATOR_PRINCIPALS)
// 调用。/v1/commands 层在 dispatch 前检 requiresOperator — 未设 env 或
// principal 不在白名单都被 OPERATOR_PRIVILEGE_REQUIRED 拒。
//
// allowed transitions:
//   - QUARANTINED → REJECTED_CONTENT_NUDITY / _POLITICS / _VIOLENCE
//   - APPROVED     → REJECTED_CONTENT_NUDITY / _POLITICS / _VIOLENCE
//                     (post-publish takedown, 不常见但需支持)
//   - REJECTED_CONTENT_* → APPROVED  (unblock)
//
// disallowed:
//   - REJECTED_TECHNICAL → 任何 CONTENT_*  (技术拒不可转内容拒, 保护 audit trail)
//   - FAILED / UPLOADING → CONTENT_*       (资产未完成处理不能走 content 门)
//   - CONTENT_* → CONTENT_* 不同类         (不双发 reject 同一 asset)
//
// audit trail: 写进 asset.LastError, 格式 'content-review:<reason>:<operator_id>'。
// 未来接 AI 内容审核会自动产生 review 事件, 在这里存原状。

type reviewMediaAssetPayload struct {
	// Reason — 取下列之一:
	//   "APPROVE"        (unblock)
	//   "REJECT_NUDITY"
	//   "REJECT_POLITICS"
	//   "REJECT_VIOLENCE"
	Reason string `json:"reason"`
	// Note — 人工 review 记录。可选, 但存 LastError 里帮 audit。
	Note string `json:"note"`
}

var reviewReasonToStatus = map[string]string{
	"APPROVE":         "APPROVED",
	"REJECT_NUDITY":   "REJECTED_CONTENT_NUDITY",
	"REJECT_POLITICS": "REJECTED_CONTENT_POLITICS",
	"REJECT_VIOLENCE": "REJECTED_CONTENT_VIOLENCE",
}

func (s *Service) reviewMediaAsset(ctx context.Context, e command.Envelope) command.Result {
	var p reviewMediaAssetPayload
	if !decode(e.Payload, &p) {
		return command.Rejected(e, "INVALID_REVIEW", "VALIDATION", "AFTER_USER_ACTION", "media.invalid_review", nil)
	}
	target, ok := reviewReasonToStatus[p.Reason]
	if !ok {
		return command.Rejected(e, "INVALID_REVIEW_REASON", "VALIDATION", "AFTER_USER_ACTION", "media.invalid_review_reason", map[string]any{"allowed": []string{"APPROVE", "REJECT_NUDITY", "REJECT_POLITICS", "REJECT_VIOLENCE"}})
	}
	asset, err := s.repository.GetAsset(ctx, e.Target.ID)
	if errors.Is(err, ErrAssetNotFound) {
		return command.Rejected(e, "MEDIA_ASSET_NOT_FOUND", "BUSINESS_STATE", "AFTER_USER_ACTION", "media.asset_not_found", nil)
	}
	if err != nil {
		return command.Rejected(e, "MEDIA_READ_FAILED", "INTERNAL", "SAFE_RETRY", "media.read_failed", nil)
	}
	// disallowed transitions
	from := asset.ModerationStatus
	if from == "REJECTED_TECHNICAL" {
		return command.Rejected(e, "MEDIA_REVIEW_DISALLOWED", "BUSINESS_STATE", "AFTER_USER_ACTION", "media.review_disallowed_technical", map[string]any{"from": from, "to": target})
	}
	if from == "UPLOADING" || from == "FAILED" || asset.ProcessingStatus == "UPLOADING" {
		return command.Rejected(e, "MEDIA_REVIEW_DISALLOWED", "BUSINESS_STATE", "AFTER_USER_ACTION", "media.review_disallowed_incomplete", map[string]any{"processingStatus": asset.ProcessingStatus})
	}
	if from == target {
		return command.Rejected(e, "MEDIA_REVIEW_NOOP", "BUSINESS_STATE", "AFTER_USER_ACTION", "media.review_noop", map[string]any{"status": from})
	}
	expectedStatus := asset.ProcessingStatus
	asset.ModerationStatus = target
	auditNote := "content-review:" + p.Reason + ":" + e.Principal.ID
	if p.Note != "" {
		auditNote = auditNote + ":" + p.Note
	}
	asset.LastError = auditNote
	asset.UpdatedAt = s.clock.Now().UTC()
	domainEvents := []event.DomainEvent{event.New("MediaAssetReviewed", "MediaAsset", asset.MediaAssetID, 1, e.Principal.ID, e.CorrelationID, e.CommandID, asset.UpdatedAt, map[string]any{
		"mediaAssetId": asset.MediaAssetID,
		"from":         from,
		"to":           target,
		"operatorId":   e.Principal.ID,
		"reason":       p.Reason,
		"note":         p.Note,
	})}
	if err := s.repository.UpdateAsset(ctx, asset, expectedStatus); err != nil {
		return command.Rejected(e, "MEDIA_UPDATE_FAILED", "INTERNAL", "SAFE_RETRY", "media.update_failed", nil)
	}
	// R15.18: 持久化决策行到 media_review_decisions 表 (memory / postgres)。
	// 失败不阻塞主命品 — audit 丢可重补, asset 状态已经定下。
	if s.reviewDecisionRepo != nil {
		decision := MediaReviewDecision{
			DecisionID:   "mrd_" + uuidHex(),
			MediaAssetID: asset.MediaAssetID,
			FromStatus:   from,
			ToStatus:     target,
			Reason:       p.Reason,
			Note:         p.Note,
			OperatorID:   e.Principal.ID,
			ReviewedAt:   asset.UpdatedAt,
		}
		if err := s.reviewDecisionRepo.AppendReviewDecision(ctx, decision); err != nil {
			// 软记录: 不返错, 只写入 result payload 的 audit warning
			domainEvents = append(domainEvents, event.New("MediaReviewDecisionPersistFailed", "MediaAsset", asset.MediaAssetID, 1, e.Principal.ID, e.CorrelationID, e.CommandID, s.clock.Now().UTC(), map[string]any{
				"mediaAssetId": asset.MediaAssetID,
				"reason":       err.Error(),
			}))
		}
	}
	return command.Accepted(e, "MediaAsset", asset.MediaAssetID, 1, target, eventRefs(domainEvents))
}

// ---------- GetMediaAsset / ListMediaAssets ----------
// 只能读自己名下的资产：storage key / URL 是敏感数据，不得跨 principal 泄露。

func (s *Service) getAsset(ctx context.Context, e command.Envelope) command.Result {
	assetID := e.Target.ID
	if assetID == "" {
		var p struct {
			MediaAssetID string `json:"mediaAssetId"`
		}
		if !decode(e.Payload, &p) || p.MediaAssetID == "" {
			return command.Rejected(e, "INVALID_ASSET_QUERY", "VALIDATION", "AFTER_USER_ACTION", "media.invalid_query", nil)
		}
		assetID = p.MediaAssetID
	}
	asset, err := s.repository.GetAsset(ctx, assetID)
	if errors.Is(err, ErrAssetNotFound) {
		return command.Rejected(e, "MEDIA_ASSET_NOT_FOUND", "BUSINESS_STATE", "AFTER_USER_ACTION", "media.asset_not_found", nil)
	}
	if err != nil {
		return command.Rejected(e, "MEDIA_READ_FAILED", "INTERNAL", "SAFE_RETRY", "media.read_failed", nil)
	}
	if asset.OwnerPrincipalID != e.Principal.ID {
		return command.Rejected(e, "MEDIA_NOT_OWNER", "AUTHORIZATION", "AFTER_USER_ACTION", "media.not_owner", nil)
	}
	return acceptedWithPayload(e, "MediaAsset", asset.MediaAssetID, 1, asset.ProcessingStatus, map[string]any{
		"asset":    asset,
		"playable": asset.ProcessingStatus == "READY", // 只有 READY 可正式播放
	}, nil)
}

func (s *Service) listAssets(ctx context.Context, e command.Envelope) command.Result {
	assets, err := s.repository.Snapshot(ctx)
	if err != nil {
		return command.Rejected(e, "MEDIA_LIST_FAILED", "INTERNAL", "SAFE_RETRY", "media.list_failed", nil)
	}
	owned := make([]MediaAsset, 0, len(assets))
	for _, asset := range assets {
		if asset.OwnerPrincipalID == e.Principal.ID {
			owned = append(owned, asset)
		}
	}
	return acceptedWithPayload(e, "MediaAsset", "", 1, "LIST", map[string]any{
		"assets": owned,
	}, nil)
}

// ---------- FFmpeg Processor（本地 dev 实现）----------

// FFmpegProcessor 用本机 ffmpeg/ffprobe 实现处理链：
// ffprobe 读元数据 → ffmpeg 转 H.264+AAC MP4+faststart → thumbnail → 存 media_store。
type FFmpegProcessor struct {
	StoreDir string // 输出目录（模拟 Object Storage）
}

func NewFFmpegProcessor(storeDir string) *FFmpegProcessor {
	return &FFmpegProcessor{StoreDir: storeDir}
}

func (p *FFmpegProcessor) Process(ctx context.Context, originalPath string) (ProcessResult, error) {
	if originalPath == "" {
		return ProcessResult{}, errors.New("original path required")
	}
	if !isSafeLocalPath(originalPath) {
		return ProcessResult{}, errors.New("original path must be a plain local file path")
	}
	if p.StoreDir == "" {
		p.StoreDir = filepath.Join(".", "media_store")
	}
	if err := os.MkdirAll(p.StoreDir, 0o755); err != nil {
		return ProcessResult{}, err
	}
	// 1. ffprobe 读元数据
	metadata, err := probe(ctx, originalPath)
	if err != nil {
		return ProcessResult{}, err
	}
	// 2. 生成输出 key（时间戳随机）
	key := strconv.FormatInt(time.Now().UnixNano(), 36)
	playbackKey := key + "_playback.mp4"
	thumbnailKey := key + "_thumb.jpg"
	playbackPath := filepath.Join(p.StoreDir, playbackKey)
	thumbnailPath := filepath.Join(p.StoreDir, thumbnailKey)
	// 3. ffmpeg 标准化：H.264 + AAC + MP4 + faststart
	if err := transcode(ctx, originalPath, playbackPath); err != nil {
		return ProcessResult{}, err
	}
	// 4. 生成缩略图
	if err := makeThumbnail(ctx, playbackPath, thumbnailPath); err != nil {
		// 缩略图失败不阻塞主链（可降级）
		_ = err
	}
	return ProcessResult{
		PlaybackStorageKey:  playbackKey,
		ThumbnailStorageKey: thumbnailKey,
		Metadata:            metadata,
	}, nil
}

func probe(ctx context.Context, path string) (VideoMetadata, error) {
	cmd := exec.CommandContext(ctx, "ffprobe", "-v", "quiet", "-print_format", "json",
		"-show_streams", "-show_format", path)
	out, err := cmd.Output()
	if err != nil {
		return VideoMetadata{}, err
	}
	var info struct {
		Streams []struct {
			CodecType string `json:"codec_type"`
			CodecName string `json:"codec_name"`
			Width     int    `json:"width"`
			Height    int    `json:"height"`
		} `json:"streams"`
		Format struct {
			Duration string `json:"duration"`
		} `json:"format"`
	}
	if err := json.Unmarshal(out, &info); err != nil {
		return VideoMetadata{}, err
	}
	meta := VideoMetadata{HasAudio: false}
	for _, stream := range info.Streams {
		if stream.CodecType == "video" {
			meta.Width = stream.Width
			meta.Height = stream.Height
			meta.Codec = stream.CodecName
		}
		if stream.CodecType == "audio" {
			meta.HasAudio = true
			meta.AudioCodec = stream.CodecName
		}
	}
	if d, err := strconv.ParseFloat(info.Format.Duration, 64); err == nil {
		meta.DurationMs = int64(d * 1000)
	}
	return meta, nil
}

func transcode(ctx context.Context, input, output string) error {
	// H.264 video + AAC audio + MP4 + faststart（兼容所有播放器）
	args := []string{"-y", "-i", input,
		"-c:v", "libx264", "-preset", "veryfast", "-crf", "23",
		"-c:a", "aac", "-b:a", "128k",
		"-movflags", "+faststart",
		"-pix_fmt", "yuv420p",
		output}
	cmd := exec.CommandContext(ctx, "ffmpeg", args...)
	if out, err := cmd.CombinedOutput(); err != nil {
		return errors.New("ffmpeg transcode failed: " + clippedOutput(out))
	}
	return nil
}

func makeThumbnail(ctx context.Context, input, output string) error {
	// 第 1 秒缩略图
	args := []string{"-y", "-i", input, "-ss", "1", "-vframes", "1", "-vf", "scale=480:-2", output}
	cmd := exec.CommandContext(ctx, "ffmpeg", args...)
	if out, err := cmd.CombinedOutput(); err != nil {
		return errors.New("thumbnail failed: " + clippedOutput(out))
	}
	return nil
}

// clippedOutput 截取 ffmpeg/ffprobe 错误输出前 200 字节。
// 注意：必须在 TrimSpace 之后再按 trim 后长度截断，否则越界 panic。
func clippedOutput(out []byte) string {
	tail := strings.TrimSpace(string(out))
	if len(tail) > 200 {
		tail = tail[:200]
	}
	return tail
}

// isSafeLocalPath 拒绝 ffmpeg 协议输入（http:// / concat: / subfile: / data: 等），
// 避免客户端可控路径变成任意文件读取 / SSRF。
func isSafeLocalPath(path string) bool {
	if strings.Contains(path, "://") {
		return false
	}
	lower := strings.ToLower(path)
	for _, prefix := range []string{"concat:", "subfile:", "data:", "file:", "lavfi:", "color:", "null:"} {
		if strings.HasPrefix(lower, prefix) {
			return false
		}
	}
	return true
}

// probeImage 用 ffprobe 读图片宽高（IMAGE 资产提供 aspect_ratio）。
func probeImage(ctx context.Context, path string) (VideoMetadata, error) {
	cmd := exec.CommandContext(ctx, "ffprobe", "-v", "quiet", "-print_format", "json",
		"-show_streams", path)
	out, err := cmd.Output()
	if err != nil {
		return VideoMetadata{}, err
	}
	var info struct {
		Streams []struct {
			CodecType string `json:"codec_type"`
			Width     int    `json:"width"`
			Height    int    `json:"height"`
		} `json:"streams"`
	}
	if err := json.Unmarshal(out, &info); err != nil {
		return VideoMetadata{}, err
	}
	meta := VideoMetadata{}
	for _, stream := range info.Streams {
		if stream.CodecType == "video" {
			meta.Width = stream.Width
			meta.Height = stream.Height
			break
		}
	}
	return meta, nil
}

// ---------- helpers ----------

func decode(payload map[string]any, target any) bool {
	raw, err := json.Marshal(payload)
	if err != nil {
		return false
	}
	if err := json.Unmarshal(raw, target); err != nil {
		return false
	}
	return true
}

func newID(prefix string) string {
	var raw [12]byte
	if _, err := rand.Read(raw[:]); err == nil {
		return prefix + hex.EncodeToString(raw[:])
	}
	return prefix + "fallback"
}

// normalizeAIGenerationSource is the boundary that maps caller
// input to the closed set we store on MediaAsset. Empty input
// becomes USER_UPLOADED (the safe default for a phone upload).
// Anything outside the closed set becomes UNKNOWN, which is the
// signal MarkMediaReady uses to fail closed per LC-06.
func normalizeAIGenerationSource(in string) string {
	switch strings.ToUpper(strings.TrimSpace(in)) {
	case "":
		return "USER_UPLOADED"
	case "USER_UPLOADED":
		return "USER_UPLOADED"
	case "AI_PERSONA":
		return "AI_PERSONA"
	case "MODEL_API":
		return "MODEL_API"
	default:
		return "UNKNOWN"
	}
}

func eventRefs(events []event.DomainEvent) []string {
	refs := make([]string, 0, len(events))
	for _, e := range events {
		refs = append(refs, e.EventID)
	}
	return refs
}

func acceptedWithPayload(e command.Envelope, aggregateType, aggregateID string, version int, state string, payload map[string]any, domainEvents []event.DomainEvent) command.Result {
	result := command.Accepted(e, aggregateType, aggregateID, version, state, eventRefs(domainEvents))
	result.OperationRef = encodeRef(payload)
	return result
}

func encodeRef(payload map[string]any) string {
	raw, _ := json.Marshal(payload)
	return string(raw)
}

// uuidHex 生成 32 字符 hex。R15.18 用于 review decision ID。
// 不用 google/uuid 库: repo 避免加依赖。
func uuidHex() string {
	var b [16]byte
	if _, err := rand.Read(b[:]); err != nil {
		// crypto/rand 不可用, 走时戳 + 纳秒 fallback
		now := time.Now().UnixNano()
		for i := 0; i < 16; i++ {
			b[i] = byte(now >> (i * 4))
		}
	}
	return hex.EncodeToString(b[:])
}

// ---------- R15.18: ListMediaReviewDecisions ----------
// operator 查 content review 决策审计行。
// 逻辑: 按 mediaAssetId 过滤,默认返回所有 (server门已限制为 operator)。
// limit 默认 100, 上限 1000。

type listMediaReviewDecisionsPayload struct {
	MediaAssetID string `json:"mediaAssetId,omitempty"`
	Limit        int    `json:"limit,omitempty"`
}

func (s *Service) listMediaReviewDecisions(ctx context.Context, e command.Envelope) command.Result {
	var p listMediaReviewDecisionsPayload
	// payload 可选 (空 = 查所有)。无法 decode = 视为空。
	if e.Payload != nil {
		_ = decode(e.Payload, &p)
	}
	if p.Limit <= 0 {
		p.Limit = 100
	}
	if p.Limit > 1000 {
		p.Limit = 1000
	}
	decisions, err := s.reviewDecisionRepo.ListReviewDecisions(ctx, p.MediaAssetID, p.Limit)
	if err != nil {
		return command.Rejected(e, "MEDIA_REVIEW_LIST_FAILED", "INTERNAL", "SAFE_RETRY", "media.review_list_failed", nil)
	}
	return acceptedWithPayload(e, "MediaReviewDecision", "", len(decisions), "LIST", map[string]any{
		"decisions":    decisions,
		"mediaAssetId": p.MediaAssetID,
		"limit":        p.Limit,
		"count":        len(decisions),
	}, nil)
}

// ---------- R15.19: AmendMediaReviewDecision ----------
// 修订决策 (append-only)。不改 prev 行的 from/to/reason/operator。
// 多 1 行: from = prev.from, to = prev.to, reason = prev.reason,
//          note = "amends:<prev_decision_id>:<amend_reason>:<amend_note>"
// 这样审计行链可用 "amends:<id>" 关系串成 revision tree。
// 修订本身: 只允许同 asset_id 范围, 防跨资产伪装。

type amendMediaReviewDecisionPayload struct {
	DecisionID  string `json:"decisionId"`
	AmendReason string `json:"amendReason"` // e.g. "NOTE_CORRECTION" / "REASON_RECLASS"
	AmendNote   string `json:"amendNote"`
}

func (s *Service) amendMediaReviewDecision(ctx context.Context, e command.Envelope) command.Result {
	var p amendMediaReviewDecisionPayload
	if !decode(e.Payload, &p) {
		return command.Rejected(e, "INVALID_AMEND", "VALIDATION", "AFTER_USER_ACTION", "media.invalid_amend", nil)
	}
	if p.DecisionID == "" {
		return command.Rejected(e, "INVALID_AMEND_DECISION_ID", "VALIDATION", "AFTER_USER_ACTION", "media.invalid_amend_decision_id", nil)
	}
	if p.AmendReason == "" {
		return command.Rejected(e, "INVALID_AMEND_REASON", "VALIDATION", "AFTER_USER_ACTION", "media.invalid_amend_reason", map[string]any{"allowed": []string{"NOTE_CORRECTION", "REASON_RECLASS"}})
	}
	prev, err := s.reviewDecisionRepo.GetReviewDecision(ctx, p.DecisionID)
	if errors.Is(err, ErrReviewDecisionNotFound) {
		return command.Rejected(e, "MEDIA_REVIEW_DECISION_NOT_FOUND", "BUSINESS_STATE", "AFTER_USER_ACTION", "media.review_decision_not_found", nil)
	}
	if err != nil {
		return command.Rejected(e, "MEDIA_REVIEW_READ_FAILED", "INTERNAL", "SAFE_RETRY", "media.review_read_failed", nil)
	}
	// Amend 跟 prev 同资产 (防跨资产)。
	if e.Target.ID != "" && e.Target.ID != prev.MediaAssetID {
		return command.Rejected(e, "MEDIA_AMEND_ASSET_MISMATCH", "VALIDATION", "AFTER_USER_ACTION", "media.amend_asset_mismatch", map[string]any{"target": e.Target.ID, "decisionAsset": prev.MediaAssetID})
	}
	now := s.clock.Now().UTC()
	amendNote := "amends:" + prev.DecisionID + ":" + p.AmendReason
	if p.AmendNote != "" {
		amendNote = amendNote + ":" + p.AmendNote
	}
	amend := MediaReviewDecision{
		DecisionID:   "mrd_" + uuidHex(),
		MediaAssetID: prev.MediaAssetID,
		FromStatus:   prev.FromStatus, // 不动
		ToStatus:     prev.ToStatus,   // 不动
		Reason:       prev.Reason,     // 不动
		Note:         amendNote,
		OperatorID:   e.Principal.ID,
		ReviewedAt:   now,
	}
	// 写入 (AppendReviewDecision 失败不阻塞 — 软 audit 丢可重补)
	if s.reviewDecisionRepo != nil {
		if err := s.reviewDecisionRepo.AppendReviewDecision(ctx, amend); err != nil {
			// 软记录
			domainEvents := []event.DomainEvent{event.New("MediaReviewDecisionAmendPersistFailed", "MediaReviewDecision", amend.DecisionID, 1, e.Principal.ID, e.CorrelationID, e.CommandID, now, map[string]any{
				"prevDecisionId": prev.DecisionID,
				"reason":         err.Error(),
			})}
			return acceptedWithPayload(e, "MediaReviewDecision", amend.DecisionID, 1, "AMEND_PERSIST_FAILED", map[string]any{
				"amend": amend,
				"error": err.Error(),
			}, domainEvents)
		}
	}
	domainEvents := []event.DomainEvent{event.New("MediaReviewDecisionAmended", "MediaReviewDecision", amend.DecisionID, 1, e.Principal.ID, e.CorrelationID, e.CommandID, now, map[string]any{
		"amendDecisionId": amend.DecisionID,
		"prevDecisionId":  prev.DecisionID,
		"amendReason":     p.AmendReason,
	})}
	return acceptedWithPayload(e, "MediaReviewDecision", amend.DecisionID, 1, "AMENDED", map[string]any{
		"amend":          amend,
		"prevDecisionId": prev.DecisionID,
	}, domainEvents)
}

// xiaomeiPersonaPhotos 是 5 小美写真在媒体仓储里的资产定义。
// URL 用相对路径（/v1/ai/personas/photo/…），客户端按当前 baseUrl
// 拼接，换网不断。APPROVED + PUBLIC + READY 才能进 Feed 读模型。
var xiaomeiPersonaPhotos = []struct {
	AssetID   string
	PersonaID string
	Path      string
}{
	{"seed_media_xiaomei_001", "ai_001", "/v1/ai/personas/photo/ai_001"},
	{"seed_media_xiaomei_002", "ai_002", "/v1/ai/personas/photo/ai_002"},
	{"seed_media_xiaomei_003", "ai_003", "/v1/ai/personas/photo/ai_003"},
	{"seed_media_xiaomei_004", "ai_004", "/v1/ai/personas/photo/ai_004"},
	{"seed_media_xiaomei_005", "ai_005", "/v1/ai/personas/photo/ai_005"},
}

// SeedXiaomeiAssets 幂等写入 5 小美写真资产（AI-POSTS-001）。
// 已存在跳过（查得到就不写），绝不覆写线上行。
func (s *Service) SeedXiaomeiAssets(ctx context.Context) error {
	now := time.Now().UTC()
	for _, p := range xiaomeiPersonaPhotos {
		if _, err := s.repository.GetAsset(ctx, p.AssetID); err == nil {
			continue
		}
		asset := MediaAsset{
			MediaAssetID:       p.AssetID,
			OwnerPrincipalType: "PLATFORM",
			OwnerPrincipalID:   "platform",
			MediaType:          "IMAGE",
			MimeType:           "image/png",
			Width:              720,
			Height:             720,
			ThumbnailURL:       p.Path,
			PlaybackURL:        p.Path,
			ModerationStatus:   "APPROVED",
			VisibilityClass:    "PUBLIC",
			ProcessingStatus:   "READY",
			AIGenerationSource: "AI_PERSONA",
			AIGenerated:        true,
			PersonaID:          p.PersonaID,
			CreatedAt:          now,
			UpdatedAt:          now,
		}
		if err := s.repository.CreateAsset(ctx, asset); err != nil {
			return err
		}
	}
	return nil
}
